"""Populate top teams with realistic squad + coach data."""
import asyncio
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from sqlalchemy import select
from app.models.team import Team

TEAM_EXTRA = {
    'ARG': {'coach': 'Lionel Scaloni', 'squad': [
        {'name': 'Emiliano Martinez', 'position': 'GK', 'number': 23, 'club': 'Aston Villa'},
        {'name': 'Cristian Romero', 'position': 'CB', 'number': 13, 'club': 'Tottenham'},
        {'name': 'Lisandro Martinez', 'position': 'CB', 'number': 25, 'club': 'Man United'},
        {'name': 'Nahuel Molina', 'position': 'RB', 'number': 26, 'club': 'Atletico Madrid'},
        {'name': 'Nicolas Tagliafico', 'position': 'LB', 'number': 3, 'club': 'Lyon'},
        {'name': 'Rodrigo De Paul', 'position': 'CM', 'number': 7, 'club': 'Atletico Madrid'},
        {'name': 'Enzo Fernandez', 'position': 'CM', 'number': 24, 'club': 'Chelsea'},
        {'name': 'Alexis Mac Allister', 'position': 'CM', 'number': 20, 'club': 'Liverpool'},
        {'name': 'Lionel Messi', 'position': 'RW', 'number': 10, 'club': 'Inter Miami'},
        {'name': 'Julian Alvarez', 'position': 'ST', 'number': 9, 'club': 'Man City'},
        {'name': 'Lautaro Martinez', 'position': 'ST', 'number': 22, 'club': 'Inter'},
    ]},
    'FRA': {'coach': 'Didier Deschamps', 'squad': [
        {'name': 'Mike Maignan', 'position': 'GK', 'number': 16, 'club': 'AC Milan'},
        {'name': 'William Saliba', 'position': 'CB', 'number': 17, 'club': 'Arsenal'},
        {'name': 'Ibrahima Konate', 'position': 'CB', 'number': 24, 'club': 'Liverpool'},
        {'name': 'Jules Kounde', 'position': 'RB', 'number': 5, 'club': 'Barcelona'},
        {'name': 'Theo Hernandez', 'position': 'LB', 'number': 22, 'club': 'AC Milan'},
        {'name': 'Aurelien Tchouameni', 'position': 'DM', 'number': 8, 'club': 'Real Madrid'},
        {'name': 'Eduardo Camavinga', 'position': 'CM', 'number': 6, 'club': 'Real Madrid'},
        {'name': 'Antoine Griezmann', 'position': 'AM', 'number': 7, 'club': 'Atletico Madrid'},
        {'name': 'Kylian Mbappe', 'position': 'ST', 'number': 10, 'club': 'Real Madrid'},
        {'name': 'Ousmane Dembele', 'position': 'RW', 'number': 11, 'club': 'PSG'},
        {'name': 'Marcus Thuram', 'position': 'ST', 'number': 9, 'club': 'Inter'},
    ]},
    'BRA': {'coach': 'Dorival Junior', 'squad': [
        {'name': 'Alisson', 'position': 'GK', 'number': 1, 'club': 'Liverpool'},
        {'name': 'Marquinhos', 'position': 'CB', 'number': 4, 'club': 'PSG'},
        {'name': 'Gabriel Magalhaes', 'position': 'CB', 'number': 3, 'club': 'Arsenal'},
        {'name': 'Danilo', 'position': 'RB', 'number': 2, 'club': 'Juventus'},
        {'name': 'Guilherme Arana', 'position': 'LB', 'number': 6, 'club': 'Atletico Mineiro'},
        {'name': 'Bruno Guimaraes', 'position': 'CM', 'number': 5, 'club': 'Newcastle'},
        {'name': 'Lucas Paqueta', 'position': 'CM', 'number': 8, 'club': 'West Ham'},
        {'name': 'Vinicius Junior', 'position': 'LW', 'number': 7, 'club': 'Real Madrid'},
        {'name': 'Rodrygo', 'position': 'RW', 'number': 11, 'club': 'Real Madrid'},
        {'name': 'Endrick', 'position': 'ST', 'number': 9, 'club': 'Real Madrid'},
        {'name': 'Raphinha', 'position': 'RW', 'number': 10, 'club': 'Barcelona'},
    ]},
    'ENG': {'coach': 'Thomas Tuchel', 'squad': [
        {'name': 'Jordan Pickford', 'position': 'GK', 'number': 1, 'club': 'Everton'},
        {'name': 'John Stones', 'position': 'CB', 'number': 5, 'club': 'Man City'},
        {'name': 'Marc Guehi', 'position': 'CB', 'number': 6, 'club': 'Crystal Palace'},
        {'name': 'Trent Alexander-Arnold', 'position': 'RB', 'number': 2, 'club': 'Liverpool'},
        {'name': 'Luke Shaw', 'position': 'LB', 'number': 3, 'club': 'Man United'},
        {'name': 'Declan Rice', 'position': 'DM', 'number': 4, 'club': 'Arsenal'},
        {'name': 'Jude Bellingham', 'position': 'CM', 'number': 10, 'club': 'Real Madrid'},
        {'name': 'Phil Foden', 'position': 'AM', 'number': 7, 'club': 'Man City'},
        {'name': 'Bukayo Saka', 'position': 'RW', 'number': 11, 'club': 'Arsenal'},
        {'name': 'Harry Kane', 'position': 'ST', 'number': 9, 'club': 'Bayern'},
        {'name': 'Cole Palmer', 'position': 'AM', 'number': 20, 'club': 'Chelsea'},
    ]},
    'GER': {'coach': 'Julian Nagelsmann', 'squad': [
        {'name': 'Manuel Neuer', 'position': 'GK', 'number': 1, 'club': 'Bayern'},
        {'name': 'Antonio Rudiger', 'position': 'CB', 'number': 2, 'club': 'Real Madrid'},
        {'name': 'Jonathan Tah', 'position': 'CB', 'number': 4, 'club': 'Leverkusen'},
        {'name': 'Joshua Kimmich', 'position': 'RB', 'number': 6, 'club': 'Bayern'},
        {'name': 'David Raum', 'position': 'LB', 'number': 3, 'club': 'RB Leipzig'},
        {'name': 'Jamal Musiala', 'position': 'AM', 'number': 10, 'club': 'Bayern'},
        {'name': 'Florian Wirtz', 'position': 'AM', 'number': 7, 'club': 'Leverkusen'},
        {'name': 'Leroy Sane', 'position': 'RW', 'number': 11, 'club': 'Bayern'},
        {'name': 'Kai Havertz', 'position': 'ST', 'number': 9, 'club': 'Arsenal'},
        {'name': 'Niclas Fullkrug', 'position': 'ST', 'number': 14, 'club': 'Dortmund'},
        {'name': 'Serge Gnabry', 'position': 'LW', 'number': 20, 'club': 'Bayern'},
    ]},
    'ESP': {'coach': 'Luis de la Fuente', 'squad': [
        {'name': 'Unai Simon', 'position': 'GK', 'number': 23, 'club': 'Athletic Bilbao'},
        {'name': 'Dani Carvajal', 'position': 'RB', 'number': 2, 'club': 'Real Madrid'},
        {'name': 'Robin Le Normand', 'position': 'CB', 'number': 3, 'club': 'Atletico Madrid'},
        {'name': 'Aymeric Laporte', 'position': 'CB', 'number': 14, 'club': 'Al Nassr'},
        {'name': 'Alejandro Grimaldo', 'position': 'LB', 'number': 12, 'club': 'Leverkusen'},
        {'name': 'Rodri', 'position': 'DM', 'number': 16, 'club': 'Man City'},
        {'name': 'Pedri', 'position': 'CM', 'number': 8, 'club': 'Barcelona'},
        {'name': 'Gavi', 'position': 'CM', 'number': 9, 'club': 'Barcelona'},
        {'name': 'Lamine Yamal', 'position': 'RW', 'number': 19, 'club': 'Barcelona'},
        {'name': 'Nico Williams', 'position': 'LW', 'number': 17, 'club': 'Athletic Bilbao'},
        {'name': 'Alvaro Morata', 'position': 'ST', 'number': 7, 'club': 'AC Milan'},
    ]},
    'POR': {'coach': 'Roberto Martinez', 'squad': [
        {'name': 'Diogo Costa', 'position': 'GK', 'number': 22, 'club': 'Porto'},
        {'name': 'Ruben Dias', 'position': 'CB', 'number': 3, 'club': 'Man City'},
        {'name': 'Goncalo Inacio', 'position': 'CB', 'number': 14, 'club': 'Sporting'},
        {'name': 'Joao Cancelo', 'position': 'RB', 'number': 2, 'club': 'Al Hilal'},
        {'name': 'Nuno Mendes', 'position': 'LB', 'number': 19, 'club': 'PSG'},
        {'name': 'Joao Palhinha', 'position': 'DM', 'number': 6, 'club': 'Bayern'},
        {'name': 'Bruno Fernandes', 'position': 'AM', 'number': 8, 'club': 'Man United'},
        {'name': 'Bernardo Silva', 'position': 'RW', 'number': 10, 'club': 'Man City'},
        {'name': 'Rafael Leao', 'position': 'LW', 'number': 17, 'club': 'AC Milan'},
        {'name': 'Cristiano Ronaldo', 'position': 'ST', 'number': 7, 'club': 'Al Nassr'},
        {'name': 'Diogo Jota', 'position': 'ST', 'number': 21, 'club': 'Liverpool'},
    ]},
    'NED': {'coach': 'Ronald Koeman', 'squad': [
        {'name': 'Bart Verbruggen', 'position': 'GK', 'number': 1, 'club': 'Brighton'},
        {'name': 'Virgil van Dijk', 'position': 'CB', 'number': 4, 'club': 'Liverpool'},
        {'name': 'Nathan Ake', 'position': 'CB', 'number': 5, 'club': 'Man City'},
        {'name': 'Denzel Dumfries', 'position': 'RB', 'number': 22, 'club': 'Inter'},
        {'name': 'Frenkie de Jong', 'position': 'CM', 'number': 21, 'club': 'Barcelona'},
        {'name': 'Ryan Gravenberch', 'position': 'CM', 'number': 8, 'club': 'Liverpool'},
        {'name': 'Tijjani Reijnders', 'position': 'CM', 'number': 14, 'club': 'AC Milan'},
        {'name': 'Xavi Simons', 'position': 'AM', 'number': 10, 'club': 'RB Leipzig'},
        {'name': 'Cody Gakpo', 'position': 'LW', 'number': 11, 'club': 'Liverpool'},
        {'name': 'Memphis Depay', 'position': 'ST', 'number': 9, 'club': 'Corinthians'},
        {'name': 'Donyell Malen', 'position': 'RW', 'number': 18, 'club': 'Aston Villa'},
    ]},
    'ITA': {'coach': 'Luciano Spalletti', 'squad': [
        {'name': 'Gianluigi Donnarumma', 'position': 'GK', 'number': 1, 'club': 'PSG'},
        {'name': 'Alessandro Bastoni', 'position': 'CB', 'number': 23, 'club': 'Inter'},
        {'name': 'Riccardo Calafiori', 'position': 'CB', 'number': 5, 'club': 'Arsenal'},
        {'name': 'Giovanni Di Lorenzo', 'position': 'RB', 'number': 2, 'club': 'Napoli'},
        {'name': 'Federico Dimarco', 'position': 'LB', 'number': 3, 'club': 'Inter'},
        {'name': 'Nicolo Barella', 'position': 'CM', 'number': 18, 'club': 'Inter'},
        {'name': 'Sandro Tonali', 'position': 'CM', 'number': 8, 'club': 'Newcastle'},
        {'name': 'Federico Chiesa', 'position': 'LW', 'number': 14, 'club': 'Liverpool'},
        {'name': 'Lorenzo Pellegrini', 'position': 'AM', 'number': 10, 'club': 'Roma'},
        {'name': 'Mateo Retegui', 'position': 'ST', 'number': 9, 'club': 'Atalanta'},
        {'name': 'Giacomo Raspadori', 'position': 'ST', 'number': 11, 'club': 'Napoli'},
    ]},
    'BEL': {'coach': 'Domenico Tedesco', 'squad': [
        {'name': 'Thibaut Courtois', 'position': 'GK', 'number': 1, 'club': 'Real Madrid'},
        {'name': 'Wout Faes', 'position': 'CB', 'number': 4, 'club': 'Leicester'},
        {'name': 'Zeno Debast', 'position': 'CB', 'number': 3, 'club': 'Sporting'},
        {'name': 'Timothy Castagne', 'position': 'RB', 'number': 21, 'club': 'Fulham'},
        {'name': 'Arthur Theate', 'position': 'LB', 'number': 5, 'club': 'Rennes'},
        {'name': 'Amadou Onana', 'position': 'DM', 'number': 6, 'club': 'Aston Villa'},
        {'name': 'Kevin De Bruyne', 'position': 'AM', 'number': 7, 'club': 'Man City'},
        {'name': 'Jeremy Doku', 'position': 'RW', 'number': 11, 'club': 'Man City'},
        {'name': 'Leandro Trossard', 'position': 'LW', 'number': 17, 'club': 'Arsenal'},
        {'name': 'Romelu Lukaku', 'position': 'ST', 'number': 9, 'club': 'Napoli'},
        {'name': 'Lois Openda', 'position': 'ST', 'number': 20, 'club': 'RB Leipzig'},
    ]},
    'URU': {'coach': 'Marcelo Bielsa', 'squad': [
        {'name': 'Sergio Rochet', 'position': 'GK', 'number': 1, 'club': 'Internacional'},
        {'name': 'Ronald Araujo', 'position': 'CB', 'number': 4, 'club': 'Barcelona'},
        {'name': 'Sebastian Caceres', 'position': 'CB', 'number': 3, 'club': 'America'},
        {'name': 'Nahitan Nandez', 'position': 'RB', 'number': 8, 'club': 'Cagliari'},
        {'name': 'Mathias Olivera', 'position': 'LB', 'number': 16, 'club': 'Napoli'},
        {'name': 'Manuel Ugarte', 'position': 'DM', 'number': 5, 'club': 'Man United'},
        {'name': 'Federico Valverde', 'position': 'CM', 'number': 15, 'club': 'Real Madrid'},
        {'name': 'Rodrigo Bentancur', 'position': 'CM', 'number': 6, 'club': 'Tottenham'},
        {'name': 'Nicolas de la Cruz', 'position': 'AM', 'number': 7, 'club': 'River Plate'},
        {'name': 'Darwin Nunez', 'position': 'ST', 'number': 9, 'club': 'Liverpool'},
        {'name': 'Maximiliano Araujo', 'position': 'LW', 'number': 13, 'club': 'Toluca'},
    ]},
    'CRO': {'coach': 'Zlatko Dalic', 'squad': [
        {'name': 'Dominik Livakovic', 'position': 'GK', 'number': 1, 'club': 'Fenerbahce'},
        {'name': 'Josko Gvardiol', 'position': 'CB', 'number': 4, 'club': 'Man City'},
        {'name': 'Josip Sutalo', 'position': 'CB', 'number': 6, 'club': 'Ajax'},
        {'name': 'Josip Stanisic', 'position': 'RB', 'number': 2, 'club': 'Bayern'},
        {'name': 'Borna Sosa', 'position': 'LB', 'number': 19, 'club': 'Ajax'},
        {'name': 'Marcelo Brozovic', 'position': 'DM', 'number': 11, 'club': 'Al Nassr'},
        {'name': 'Luka Modric', 'position': 'CM', 'number': 10, 'club': 'Real Madrid'},
        {'name': 'Mateo Kovacic', 'position': 'CM', 'number': 8, 'club': 'Man City'},
        {'name': 'Lovro Majer', 'position': 'AM', 'number': 7, 'club': 'Wolfsburg'},
        {'name': 'Andrej Kramaric', 'position': 'ST', 'number': 9, 'club': 'Hoffenheim'},
        {'name': 'Ivan Perisic', 'position': 'LW', 'number': 14, 'club': 'Hajduk Split'},
    ]},
    'USA': {'coach': 'Mauricio Pochettino', 'squad': [
        {'name': 'Matt Turner', 'position': 'GK', 'number': 1, 'club': 'Arsenal'},
        {'name': 'Antonee Robinson', 'position': 'LB', 'number': 5, 'club': 'Fulham'},
        {'name': 'Chris Richards', 'position': 'CB', 'number': 3, 'club': 'Crystal Palace'},
        {'name': 'Sergino Dest', 'position': 'RB', 'number': 2, 'club': 'PSV'},
        {'name': 'Weston McKennie', 'position': 'CM', 'number': 8, 'club': 'Juventus'},
        {'name': 'Yunus Musah', 'position': 'CM', 'number': 6, 'club': 'AC Milan'},
        {'name': 'Tyler Adams', 'position': 'DM', 'number': 4, 'club': 'Bournemouth'},
        {'name': 'Christian Pulisic', 'position': 'LW', 'number': 10, 'club': 'AC Milan'},
        {'name': 'Gio Reyna', 'position': 'AM', 'number': 7, 'club': 'Dortmund'},
        {'name': 'Timothy Weah', 'position': 'RW', 'number': 21, 'club': 'Juventus'},
        {'name': 'Folarin Balogun', 'position': 'ST', 'number': 9, 'club': 'Monaco'},
    ]},
    'MEX': {'coach': 'Javier Aguirre', 'squad': [
        {'name': 'Guillermo Ochoa', 'position': 'GK', 'number': 13, 'club': 'Salernitana'},
        {'name': 'Cesar Montes', 'position': 'CB', 'number': 3, 'club': 'Almeria'},
        {'name': 'Johan Vasquez', 'position': 'CB', 'number': 5, 'club': 'Genoa'},
        {'name': 'Jorge Sanchez', 'position': 'RB', 'number': 2, 'club': 'Porto'},
        {'name': 'Jesus Gallardo', 'position': 'LB', 'number': 23, 'club': 'Monterrey'},
        {'name': 'Edson Alvarez', 'position': 'DM', 'number': 4, 'club': 'West Ham'},
        {'name': 'Luis Chavez', 'position': 'CM', 'number': 18, 'club': 'Dynamo Moscow'},
        {'name': 'Orbelin Pineda', 'position': 'CM', 'number': 17, 'club': 'AEK Athens'},
        {'name': 'Hirving Lozano', 'position': 'RW', 'number': 11, 'club': 'PSV'},
        {'name': 'Santiago Gimenez', 'position': 'ST', 'number': 9, 'club': 'AC Milan'},
        {'name': 'Alexis Vega', 'position': 'LW', 'number': 10, 'club': 'Toluca'},
    ]},
    'JPN': {'coach': 'Hajime Moriyasu', 'squad': [
        {'name': 'Zion Suzuki', 'position': 'GK', 'number': 1, 'club': 'Parma'},
        {'name': 'Takehiro Tomiyasu', 'position': 'CB', 'number': 22, 'club': 'Arsenal'},
        {'name': 'Ko Itakura', 'position': 'CB', 'number': 4, 'club': 'Gladbach'},
        {'name': 'Yukinari Sugawara', 'position': 'RB', 'number': 2, 'club': 'Southampton'},
        {'name': 'Hiroki Ito', 'position': 'LB', 'number': 3, 'club': 'Bayern'},
        {'name': 'Wataru Endo', 'position': 'DM', 'number': 6, 'club': 'Liverpool'},
        {'name': 'Daichi Kamada', 'position': 'CM', 'number': 15, 'club': 'Crystal Palace'},
        {'name': 'Takefusa Kubo', 'position': 'RW', 'number': 11, 'club': 'Real Sociedad'},
        {'name': 'Kaoru Mitoma', 'position': 'LW', 'number': 7, 'club': 'Brighton'},
        {'name': 'Ritsu Doan', 'position': 'RW', 'number': 10, 'club': 'Freiburg'},
        {'name': 'Ayase Ueda', 'position': 'ST', 'number': 9, 'club': 'Feyenoord'},
    ]},
    'KOR': {'coach': 'Hong Myung-bo', 'squad': [
        {'name': 'Kim Seung-gyu', 'position': 'GK', 'number': 1, 'club': 'Al Shabab'},
        {'name': 'Kim Min-jae', 'position': 'CB', 'number': 4, 'club': 'Bayern'},
        {'name': 'Kim Young-gwon', 'position': 'CB', 'number': 19, 'club': 'Ulsan HD'},
        {'name': 'Seol Young-woo', 'position': 'RB', 'number': 2, 'club': 'Red Star'},
        {'name': 'Lee Ki-je', 'position': 'LB', 'number': 3, 'club': 'Suwon'},
        {'name': 'Hwang In-beom', 'position': 'CM', 'number': 6, 'club': 'Feyenoord'},
        {'name': 'Lee Kang-in', 'position': 'AM', 'number': 18, 'club': 'PSG'},
        {'name': 'Son Heung-min', 'position': 'LW', 'number': 7, 'club': 'Tottenham'},
        {'name': 'Hwang Hee-chan', 'position': 'RW', 'number': 11, 'club': 'Wolves'},
        {'name': 'Cho Gue-sung', 'position': 'ST', 'number': 9, 'club': 'Midtjylland'},
        {'name': 'Lee Jae-sung', 'position': 'AM', 'number': 10, 'club': 'Mainz'},
    ]},
    'CAN': {'coach': 'Jesse Marsch', 'squad': [
        {'name': 'Maxime Crepeau', 'position': 'GK', 'number': 1, 'club': 'Portland'},
        {'name': 'Alistair Johnston', 'position': 'RB', 'number': 2, 'club': 'Celtic'},
        {'name': 'Moise Bombito', 'position': 'CB', 'number': 5, 'club': 'Nice'},
        {'name': 'Derek Cornelius', 'position': 'CB', 'number': 4, 'club': 'Marseille'},
        {'name': 'Alphonso Davies', 'position': 'LB', 'number': 19, 'club': 'Real Madrid'},
        {'name': 'Stephen Eustaquio', 'position': 'DM', 'number': 7, 'club': 'Porto'},
        {'name': 'Ismael Kone', 'position': 'CM', 'number': 8, 'club': 'Rennes'},
        {'name': 'Tajon Buchanan', 'position': 'RW', 'number': 11, 'club': 'Inter'},
        {'name': 'Jonathan David', 'position': 'ST', 'number': 9, 'club': 'Lille'},
        {'name': 'Cyle Larin', 'position': 'ST', 'number': 10, 'club': 'Mallorca'},
        {'name': 'Liam Millar', 'position': 'LW', 'number': 23, 'club': 'Basel'},
    ]},
}

async def main():
    engine = create_async_engine(
        'postgresql+asyncpg://wcp:wcp_dev@localhost:5432/world_cup_predictor'
    )
    session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with session() as db:
        for code, data in TEAM_EXTRA.items():
            result = await db.execute(select(Team).where(Team.fifa_code == code))
            team = result.scalar_one_or_none()
            if team:
                team.coach_name = data['coach']
                team.squad_json = data['squad']
                print(f'Updated {team.name}: coach={data["coach"]}, {len(data["squad"])} players')
        await db.commit()
    await engine.dispose()
    print('Done')

asyncio.run(main())
