"""Populate ALL 48 teams with full 23-man squads + coaches + availability status."""
import asyncio
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from sqlalchemy import select
from app.models.team import Team

# Full squad data for all 48 World Cup 2026 teams
# Each team: coach name + 23 players with position, number, club, status
ALL_TEAMS = {
    "ARG": {"coach": "Lionel Scaloni", "squad": [
        ("Emiliano Martinez", "GK", 23, "Aston Villa", "fit"),
        ("Franco Armani", "GK", 1, "River Plate", "fit"),
        ("Geronimo Rulli", "GK", 12, "Marseille", "fit"),
        ("Cristian Romero", "CB", 13, "Tottenham", "fit"),
        ("Nicolas Otamendi", "CB", 19, "Benfica", "fit"),
        ("Lisandro Martinez", "CB", 25, "Man United", "doubtful"),
        ("German Pezzella", "CB", 6, "River Plate", "fit"),
        ("Nahuel Molina", "RB", 26, "Atletico Madrid", "fit"),
        ("Gonzalo Montiel", "RB", 4, "Sevilla", "fit"),
        ("Nicolas Tagliafico", "LB", 3, "Lyon", "fit"),
        ("Marcos Acuna", "LB", 8, "Sevilla", "fit"),
        ("Rodrigo De Paul", "CM", 7, "Atletico Madrid", "fit"),
        ("Enzo Fernandez", "CM", 24, "Chelsea", "fit"),
        ("Alexis Mac Allister", "CM", 20, "Liverpool", "fit"),
        ("Leandro Paredes", "DM", 5, "Roma", "fit"),
        ("Giovani Lo Celso", "AM", 16, "Tottenham", "fit"),
        ("Exequiel Palacios", "CM", 14, "Leverkusen", "fit"),
        ("Lionel Messi", "RW", 10, "Inter Miami", "fit"),
        ("Angel Di Maria", "LW", 11, "Benfica", "fit"),
        ("Julian Alvarez", "ST", 9, "Man City", "fit"),
        ("Lautaro Martinez", "ST", 22, "Inter", "fit"),
        ("Nicolas Gonzalez", "LW", 15, "Juventus", "fit"),
        ("Alejandro Garnacho", "LW", 17, "Man United", "fit"),
    ]},
    "FRA": {"coach": "Didier Deschamps", "squad": [
        ("Mike Maignan", "GK", 16, "AC Milan", "fit"),
        ("Brice Samba", "GK", 1, "Lens", "fit"),
        ("Alphonse Areola", "GK", 23, "West Ham", "fit"),
        ("William Saliba", "CB", 17, "Arsenal", "fit"),
        ("Ibrahima Konate", "CB", 24, "Liverpool", "fit"),
        ("Dayot Upamecano", "CB", 4, "Bayern", "fit"),
        ("Jules Kounde", "RB", 5, "Barcelona", "fit"),
        ("Benjamin Pavard", "RB", 2, "Inter", "fit"),
        ("Theo Hernandez", "LB", 22, "AC Milan", "fit"),
        ("Lucas Hernandez", "LB", 21, "PSG", "injured"),
        ("Aurelien Tchouameni", "DM", 8, "Real Madrid", "fit"),
        ("Eduardo Camavinga", "CM", 6, "Real Madrid", "fit"),
        ("Adrien Rabiot", "CM", 14, "Marseille", "fit"),
        ("Youssouf Fofana", "CM", 19, "AC Milan", "fit"),
        ("Warren Zaire-Emery", "CM", 18, "PSG", "fit"),
        ("Antoine Griezmann", "AM", 7, "Atletico Madrid", "fit"),
        ("Kylian Mbappe", "ST", 10, "Real Madrid", "fit"),
        ("Ousmane Dembele", "RW", 11, "PSG", "fit"),
        ("Randal Kolo Muani", "ST", 12, "Juventus", "fit"),
        ("Marcus Thuram", "ST", 9, "Inter", "fit"),
        ("Kingsley Coman", "RW", 20, "Bayern", "fit"),
        ("Bradley Barcola", "LW", 25, "PSG", "fit"),
        ("Michael Olise", "RW", 15, "Bayern", "fit"),
    ]},
    "BRA": {"coach": "Dorival Junior", "squad": [
        ("Alisson", "GK", 1, "Liverpool", "fit"),
        ("Ederson", "GK", 23, "Man City", "fit"),
        ("Bento", "GK", 12, "Al Nassr", "fit"),
        ("Marquinhos", "CB", 4, "PSG", "fit"),
        ("Eder Militao", "CB", 14, "Real Madrid", "injured"),
        ("Gabriel Magalhaes", "CB", 3, "Arsenal", "fit"),
        ("Bremer", "CB", 22, "Juventus", "fit"),
        ("Danilo", "RB", 2, "Juventus", "fit"),
        ("Vanderson", "RB", 13, "Monaco", "fit"),
        ("Guilherme Arana", "LB", 6, "Atletico Mineiro", "fit"),
        ("Alex Telles", "LB", 16, "Al Nassr", "fit"),
        ("Bruno Guimaraes", "CM", 5, "Newcastle", "fit"),
        ("Lucas Paqueta", "CM", 8, "West Ham", "fit"),
        ("Joelinton", "CM", 17, "Newcastle", "fit"),
        ("Andre", "DM", 15, "Wolves", "fit"),
        ("Vinicius Junior", "LW", 7, "Real Madrid", "fit"),
        ("Rodrygo", "RW", 11, "Real Madrid", "fit"),
        ("Raphinha", "RW", 10, "Barcelona", "fit"),
        ("Gabriel Martinelli", "LW", 21, "Arsenal", "fit"),
        ("Endrick", "ST", 9, "Real Madrid", "fit"),
        ("Gabriel Jesus", "ST", 18, "Arsenal", "fit"),
        ("Savinho", "RW", 20, "Man City", "fit"),
        ("Luiz Henrique", "LW", 24, "Botafogo", "fit"),
    ]},
    "ENG": {"coach": "Thomas Tuchel", "squad": [
        ("Jordan Pickford", "GK", 1, "Everton", "fit"),
        ("Aaron Ramsdale", "GK", 13, "Southampton", "fit"),
        ("Dean Henderson", "GK", 23, "Crystal Palace", "fit"),
        ("John Stones", "CB", 5, "Man City", "fit"),
        ("Marc Guehi", "CB", 6, "Crystal Palace", "fit"),
        ("Ezri Konsa", "CB", 15, "Aston Villa", "fit"),
        ("Levi Colwill", "CB", 21, "Chelsea", "fit"),
        ("Trent Alexander-Arnold", "RB", 2, "Liverpool", "fit"),
        ("Reece James", "RB", 16, "Chelsea", "doubtful"),
        ("Luke Shaw", "LB", 3, "Man United", "fit"),
        ("Lewis Hall", "LB", 12, "Newcastle", "fit"),
        ("Declan Rice", "DM", 4, "Arsenal", "fit"),
        ("Jude Bellingham", "CM", 10, "Real Madrid", "fit"),
        ("Phil Foden", "AM", 7, "Man City", "fit"),
        ("Cole Palmer", "AM", 20, "Chelsea", "fit"),
        ("Conor Gallagher", "CM", 17, "Atletico Madrid", "fit"),
        ("Kobbie Mainoo", "CM", 14, "Man United", "fit"),
        ("Bukayo Saka", "RW", 11, "Arsenal", "fit"),
        ("Harry Kane", "ST", 9, "Bayern", "fit"),
        ("Ollie Watkins", "ST", 18, "Aston Villa", "fit"),
        ("Anthony Gordon", "LW", 19, "Newcastle", "fit"),
        ("Jarrod Bowen", "RW", 22, "West Ham", "fit"),
        ("Jack Grealish", "LW", 8, "Man City", "fit"),
    ]},
    "GER": {"coach": "Julian Nagelsmann", "squad": [
        ("Manuel Neuer", "GK", 1, "Bayern", "fit"),
        ("Marc-Andre ter Stegen", "GK", 22, "Barcelona", "injured"),
        ("Oliver Baumann", "GK", 12, "Hoffenheim", "fit"),
        ("Antonio Rudiger", "CB", 2, "Real Madrid", "fit"),
        ("Jonathan Tah", "CB", 4, "Leverkusen", "fit"),
        ("Nico Schlotterbeck", "CB", 15, "Dortmund", "fit"),
        ("Waldemar Anton", "CB", 3, "Dortmund", "fit"),
        ("Joshua Kimmich", "RB", 6, "Bayern", "fit"),
        ("Benjamin Henrichs", "RB", 16, "RB Leipzig", "fit"),
        ("David Raum", "LB", 3, "RB Leipzig", "fit"),
        ("Maximilian Mittelstadt", "LB", 18, "Stuttgart", "fit"),
        ("Robert Andrich", "DM", 23, "Leverkusen", "fit"),
        ("Pascal Gross", "CM", 5, "Dortmund", "fit"),
        ("Aleksandar Pavlovic", "CM", 20, "Bayern", "fit"),
        ("Jamal Musiala", "AM", 10, "Bayern", "fit"),
        ("Florian Wirtz", "AM", 7, "Leverkusen", "fit"),
        ("Leroy Sane", "RW", 11, "Bayern", "fit"),
        ("Kai Havertz", "ST", 9, "Arsenal", "fit"),
        ("Niclas Fullkrug", "ST", 14, "Dortmund", "fit"),
        ("Serge Gnabry", "LW", 17, "Bayern", "fit"),
        ("Deniz Undav", "ST", 21, "Stuttgart", "fit"),
        ("Chris Fuhrich", "LW", 13, "Stuttgart", "fit"),
        ("Maximilian Beier", "ST", 19, "Dortmund", "fit"),
    ]},
    "ESP": {"coach": "Luis de la Fuente", "squad": [
        ("Unai Simon", "GK", 23, "Athletic Bilbao", "fit"),
        ("David Raya", "GK", 1, "Arsenal", "fit"),
        ("Alex Remiro", "GK", 13, "Real Sociedad", "fit"),
        ("Dani Carvajal", "RB", 2, "Real Madrid", "fit"),
        ("Pedro Porro", "RB", 15, "Tottenham", "fit"),
        ("Robin Le Normand", "CB", 3, "Atletico Madrid", "fit"),
        ("Aymeric Laporte", "CB", 14, "Al Nassr", "fit"),
        ("Pau Cubarsi", "CB", 4, "Barcelona", "fit"),
        ("Alejandro Grimaldo", "LB", 12, "Leverkusen", "fit"),
        ("Marc Cucurella", "LB", 17, "Chelsea", "fit"),
        ("Rodri", "DM", 16, "Man City", "injured"),
        ("Martin Zubimendi", "DM", 18, "Real Sociedad", "fit"),
        ("Pedri", "CM", 8, "Barcelona", "fit"),
        ("Gavi", "CM", 9, "Barcelona", "fit"),
        ("Fabian Ruiz", "CM", 6, "PSG", "fit"),
        ("Dani Olmo", "AM", 10, "Barcelona", "fit"),
        ("Lamine Yamal", "RW", 19, "Barcelona", "fit"),
        ("Nico Williams", "LW", 11, "Athletic Bilbao", "fit"),
        ("Alvaro Morata", "ST", 7, "AC Milan", "fit"),
        ("Mikel Oyarzabal", "ST", 21, "Real Sociedad", "fit"),
        ("Joselu", "ST", 22, "Al Gharafa", "fit"),
        ("Ferran Torres", "RW", 20, "Barcelona", "fit"),
        ("Yeremy Pino", "RW", 25, "Villarreal", "fit"),
    ]},
    "POR": {"coach": "Roberto Martinez", "squad": [
        ("Diogo Costa", "GK", 22, "Porto", "fit"),
        ("Rui Patricio", "GK", 1, "Roma", "fit"),
        ("Jose Sa", "GK", 12, "Wolves", "fit"),
        ("Ruben Dias", "CB", 3, "Man City", "fit"),
        ("Goncalo Inacio", "CB", 14, "Sporting", "fit"),
        ("Antonio Silva", "CB", 4, "Benfica", "fit"),
        ("Danilo Pereira", "CB", 13, "Al Ittihad", "fit"),
        ("Joao Cancelo", "RB", 2, "Al Hilal", "fit"),
        ("Nelson Semedo", "RB", 5, "Wolves", "fit"),
        ("Nuno Mendes", "LB", 19, "PSG", "fit"),
        ("Diogo Dalot", "LB", 20, "Man United", "fit"),
        ("Joao Palhinha", "DM", 6, "Bayern", "fit"),
        ("Ruben Neves", "CM", 18, "Al Hilal", "fit"),
        ("Vitinha", "CM", 23, "PSG", "fit"),
        ("Bruno Fernandes", "AM", 8, "Man United", "fit"),
        ("Bernardo Silva", "RW", 10, "Man City", "fit"),
        ("Rafael Leao", "LW", 17, "AC Milan", "fit"),
        ("Pedro Neto", "RW", 25, "Chelsea", "fit"),
        ("Cristiano Ronaldo", "ST", 7, "Al Nassr", "fit"),
        ("Diogo Jota", "ST", 21, "Liverpool", "fit"),
        ("Goncalo Ramos", "ST", 9, "PSG", "fit"),
        ("Joao Felix", "AM", 11, "Chelsea", "fit"),
        ("Francisco Conceicao", "RW", 15, "Juventus", "fit"),
    ]},
    "NED": {"coach": "Ronald Koeman", "squad": [
        ("Bart Verbruggen", "GK", 1, "Brighton", "fit"),
        ("Mark Flekken", "GK", 13, "Brentford", "fit"),
        ("Justin Bijlow", "GK", 23, "Feyenoord", "fit"),
        ("Virgil van Dijk", "CB", 4, "Liverpool", "fit"),
        ("Nathan Ake", "CB", 5, "Man City", "fit"),
        ("Matthijs de Ligt", "CB", 3, "Man United", "fit"),
        ("Micky van de Ven", "CB", 15, "Tottenham", "fit"),
        ("Denzel Dumfries", "RB", 22, "Inter", "fit"),
        ("Jeremie Frimpong", "RB", 18, "Leverkusen", "fit"),
        ("Lutsharel Geertruida", "LB", 2, "RB Leipzig", "fit"),
        ("Quilindschy Hartman", "LB", 16, "Feyenoord", "fit"),
        ("Frenkie de Jong", "CM", 21, "Barcelona", "fit"),
        ("Tijjani Reijnders", "CM", 14, "AC Milan", "fit"),
        ("Ryan Gravenberch", "CM", 8, "Liverpool", "fit"),
        ("Marten de Roon", "DM", 20, "Atalanta", "fit"),
        ("Teun Koopmeiners", "CM", 10, "Juventus", "fit"),
        ("Xavi Simons", "AM", 7, "RB Leipzig", "fit"),
        ("Cody Gakpo", "LW", 11, "Liverpool", "fit"),
        ("Memphis Depay", "ST", 9, "Corinthians", "fit"),
        ("Donyell Malen", "RW", 17, "Aston Villa", "fit"),
        ("Wout Weghorst", "ST", 19, "Ajax", "fit"),
        ("Brian Brobbey", "ST", 6, "Ajax", "fit"),
        ("Noa Lang", "LW", 25, "PSV", "fit"),
    ]},
    "ITA": {"coach": "Luciano Spalletti", "squad": [
        ("Gianluigi Donnarumma", "GK", 1, "PSG", "fit"),
        ("Guglielmo Vicario", "GK", 12, "Tottenham", "fit"),
        ("Alex Meret", "GK", 21, "Napoli", "fit"),
        ("Alessandro Bastoni", "CB", 23, "Inter", "fit"),
        ("Riccardo Calafiori", "CB", 5, "Arsenal", "fit"),
        ("Alessandro Buongiorno", "CB", 4, "Napoli", "fit"),
        ("Giorgio Scalvini", "CB", 15, "Atalanta", "injured"),
        ("Giovanni Di Lorenzo", "RB", 2, "Napoli", "fit"),
        ("Matteo Darmian", "RB", 13, "Inter", "fit"),
        ("Federico Dimarco", "LB", 3, "Inter", "fit"),
        ("Andrea Cambiaso", "LB", 20, "Juventus", "fit"),
        ("Nicolo Barella", "CM", 18, "Inter", "fit"),
        ("Sandro Tonali", "CM", 8, "Newcastle", "fit"),
        ("Davide Frattesi", "CM", 16, "Inter", "fit"),
        ("Samuele Ricci", "DM", 6, "Torino", "fit"),
        ("Lorenzo Pellegrini", "AM", 10, "Roma", "fit"),
        ("Federico Chiesa", "LW", 14, "Liverpool", "doubtful"),
        ("Giacomo Raspadori", "ST", 11, "Napoli", "fit"),
        ("Mateo Retegui", "ST", 9, "Atalanta", "fit"),
        ("Moise Kean", "ST", 19, "Fiorentina", "fit"),
        ("Nicolo Zaniolo", "AM", 22, "Atalanta", "fit"),
        ("Mattia Zaccagni", "LW", 17, "Lazio", "fit"),
        ("Destiny Udogie", "LB", 7, "Tottenham", "fit"),
    ]},
    "BEL": {"coach": "Domenico Tedesco", "squad": [
        ("Thibaut Courtois", "GK", 1, "Real Madrid", "fit"),
        ("Koen Casteels", "GK", 13, "Al Qadsiah", "fit"),
        ("Matz Sels", "GK", 12, "Nottm Forest", "fit"),
        ("Wout Faes", "CB", 4, "Leicester", "fit"),
        ("Zeno Debast", "CB", 3, "Sporting", "fit"),
        ("Jan Vertonghen", "CB", 5, "Anderlecht", "fit"),
        ("Ameen Al-Dakhil", "CB", 2, "Burnley", "fit"),
        ("Timothy Castagne", "RB", 21, "Fulham", "fit"),
        ("Thomas Meunier", "RB", 15, "Lille", "fit"),
        ("Arthur Theate", "LB", 5, "Rennes", "fit"),
        ("Maxim De Cuyper", "LB", 22, "Club Brugge", "fit"),
        ("Amadou Onana", "DM", 6, "Aston Villa", "fit"),
        ("Youri Tielemans", "CM", 8, "Aston Villa", "fit"),
        ("Orel Mangala", "CM", 20, "Everton", "fit"),
        ("Kevin De Bruyne", "AM", 7, "Man City", "fit"),
        ("Charles De Ketelaere", "AM", 14, "Atalanta", "fit"),
        ("Jeremy Doku", "RW", 11, "Man City", "fit"),
        ("Leandro Trossard", "LW", 17, "Arsenal", "fit"),
        ("Romelu Lukaku", "ST", 9, "Napoli", "fit"),
        ("Lois Openda", "ST", 20, "RB Leipzig", "fit"),
        ("Johan Bakayoko", "RW", 19, "PSV", "fit"),
        ("Dodi Lukebakio", "RW", 16, "Sevilla", "fit"),
        ("Alexis Saelemaekers", "LW", 18, "AC Milan", "fit"),
    ]},
    "URU": {"coach": "Marcelo Bielsa", "squad": [
        ("Sergio Rochet", "GK", 1, "Internacional", "fit"),
        ("Franco Israel", "GK", 12, "Sporting", "fit"),
        ("Santiago Mele", "GK", 23, "Junior", "fit"),
        ("Ronald Araujo", "CB", 4, "Barcelona", "fit"),
        ("Sebastian Caceres", "CB", 3, "America", "fit"),
        ("Mathias Olivera", "CB", 16, "Napoli", "fit"),
        ("Jose Maria Gimenez", "CB", 2, "Atletico Madrid", "fit"),
        ("Nahitan Nandez", "RB", 8, "Cagliari", "fit"),
        ("Guillermo Varela", "RB", 13, "Flamengo", "fit"),
        ("Joaquin Piquerez", "LB", 17, "Palmeiras", "fit"),
        ("Lucas Olaza", "LB", 22, "Krasnodar", "fit"),
        ("Manuel Ugarte", "DM", 5, "Man United", "fit"),
        ("Federico Valverde", "CM", 15, "Real Madrid", "fit"),
        ("Rodrigo Bentancur", "CM", 6, "Tottenham", "fit"),
        ("Giorgian de Arrascaeta", "AM", 10, "Flamengo", "fit"),
        ("Nicolas de la Cruz", "AM", 7, "River Plate", "fit"),
        ("Maximiliano Araujo", "LW", 14, "Toluca", "fit"),
        ("Facundo Pellistri", "RW", 18, "Granada", "fit"),
        ("Darwin Nunez", "ST", 9, "Liverpool", "fit"),
        ("Federico Vinas", "ST", 19, "Leon", "fit"),
        ("Cristian Olivera", "RW", 20, "Los Angeles FC", "fit"),
        ("Brian Rodriguez", "LW", 11, "America", "fit"),
        ("Luis Suarez", "ST", 21, "Inter Miami", "doubtful"),
    ]},
    "CRO": {"coach": "Zlatko Dalic", "squad": [
        ("Dominik Livakovic", "GK", 1, "Fenerbahce", "fit"),
        ("Ivica Ivusic", "GK", 12, "Pafos", "fit"),
        ("Nediljko Labrovic", "GK", 23, "Augsburg", "fit"),
        ("Josko Gvardiol", "CB", 4, "Man City", "fit"),
        ("Josip Sutalo", "CB", 6, "Ajax", "fit"),
        ("Martin Erlic", "CB", 3, "Bologna", "fit"),
        ("Marin Pongracic", "CB", 5, "Fiorentina", "fit"),
        ("Josip Stanisic", "RB", 2, "Bayern", "fit"),
        ("Josip Juranovic", "RB", 22, "Union Berlin", "fit"),
        ("Borna Sosa", "LB", 19, "Ajax", "fit"),
        ("Domagoj Bradaric", "LB", 14, "Salernitana", "fit"),
        ("Marcelo Brozovic", "DM", 11, "Al Nassr", "fit"),
        ("Luka Modric", "CM", 10, "Real Madrid", "fit"),
        ("Mateo Kovacic", "CM", 8, "Man City", "fit"),
        ("Mario Pasalic", "CM", 15, "Atalanta", "fit"),
        ("Lovro Majer", "AM", 7, "Wolfsburg", "fit"),
        ("Luka Sucic", "CM", 25, "Real Sociedad", "fit"),
        ("Ivan Perisic", "LW", 14, "Hajduk Split", "fit"),
        ("Andrej Kramaric", "ST", 9, "Hoffenheim", "fit"),
        ("Bruno Petkovic", "ST", 17, "Dinamo Zagreb", "fit"),
        ("Ante Budimir", "ST", 18, "Osasuna", "fit"),
        ("Marko Pjaca", "LW", 20, "Rijeka", "fit"),
        ("Marco Pasalic", "RW", 21, "Como", "fit"),
    ]},
    "USA": {"coach": "Mauricio Pochettino", "squad": [
        ("Matt Turner", "GK", 1, "Arsenal", "fit"),
        ("Ethan Horvath", "GK", 18, "Cardiff", "fit"),
        ("Gaga Slonina", "GK", 22, "Chelsea", "fit"),
        ("Antonee Robinson", "LB", 5, "Fulham", "fit"),
        ("Chris Richards", "CB", 3, "Crystal Palace", "fit"),
        ("Tim Ream", "CB", 13, "Charlotte", "fit"),
        ("Cameron Carter-Vickers", "CB", 20, "Celtic", "fit"),
        ("Sergino Dest", "RB", 2, "PSV", "injured"),
        ("Joe Scally", "RB", 12, "Gladbach", "fit"),
        ("Kristoffer Lund", "LB", 19, "Palermo", "fit"),
        ("Auston Trusty", "CB", 15, "Sheff Utd", "fit"),
        ("Weston McKennie", "CM", 8, "Juventus", "fit"),
        ("Yunus Musah", "CM", 6, "AC Milan", "fit"),
        ("Tyler Adams", "DM", 4, "Bournemouth", "fit"),
        ("Johnny Cardoso", "DM", 14, "Real Betis", "fit"),
        ("Malik Tillman", "AM", 17, "PSV", "fit"),
        ("Gio Reyna", "AM", 7, "Dortmund", "fit"),
        ("Christian Pulisic", "LW", 10, "AC Milan", "fit"),
        ("Timothy Weah", "RW", 21, "Juventus", "fit"),
        ("Folarin Balogun", "ST", 9, "Monaco", "fit"),
        ("Ricardo Pepi", "ST", 16, "PSV", "fit"),
        ("Brenden Aaronson", "AM", 11, "Leeds", "fit"),
        ("Haji Wright", "ST", 24, "Coventry", "fit"),
    ]},
    "MEX": {"coach": "Javier Aguirre", "squad": [
        ("Guillermo Ochoa", "GK", 13, "Salernitana", "fit"),
        ("Luis Malagon", "GK", 1, "America", "fit"),
        ("Carlos Acevedo", "GK", 12, "Santos Laguna", "fit"),
        ("Cesar Montes", "CB", 3, "Almeria", "fit"),
        ("Johan Vasquez", "CB", 5, "Genoa", "fit"),
        ("Israel Reyes", "CB", 15, "America", "fit"),
        ("Victor Guzman", "CB", 22, "Monterrey", "fit"),
        ("Jorge Sanchez", "RB", 2, "Porto", "fit"),
        ("Kevin Alvarez", "RB", 19, "America", "fit"),
        ("Jesus Gallardo", "LB", 23, "Monterrey", "fit"),
        ("Gerardo Arteaga", "LB", 6, "Genk", "fit"),
        ("Edson Alvarez", "DM", 4, "West Ham", "fit"),
        ("Luis Chavez", "CM", 18, "Dynamo Moscow", "fit"),
        ("Orbelin Pineda", "CM", 17, "AEK Athens", "fit"),
        ("Carlos Rodriguez", "CM", 7, "Cruz Azul", "fit"),
        ("Erick Sanchez", "CM", 14, "America", "fit"),
        ("Hirving Lozano", "RW", 11, "PSV", "fit"),
        ("Santiago Gimenez", "ST", 9, "AC Milan", "fit"),
        ("Alexis Vega", "LW", 10, "Toluca", "fit"),
        ("Julian Quinones", "ST", 20, "Al Qadsiah", "fit"),
        ("Uriel Antuna", "RW", 21, "Cruz Azul", "fit"),
        ("Cesar Huerta", "LW", 16, "Pumas", "fit"),
        ("Raul Jimenez", "ST", 8, "Fulham", "fit"),
    ]},
    "JPN": {"coach": "Hajime Moriyasu", "squad": [
        ("Zion Suzuki", "GK", 1, "Parma", "fit"),
        ("Keisuke Osako", "GK", 12, "Sanfrecce", "fit"),
        ("Kosei Tani", "GK", 23, "Machida", "fit"),
        ("Takehiro Tomiyasu", "CB", 22, "Arsenal", "fit"),
        ("Ko Itakura", "CB", 4, "Gladbach", "fit"),
        ("Shogo Taniguchi", "CB", 3, "Al Rayyan", "fit"),
        ("Hiroki Ito", "CB", 2, "Bayern", "fit"),
        ("Yukinari Sugawara", "RB", 19, "Southampton", "fit"),
        ("Ryo Hatsuse", "LB", 21, "Sheff Wed", "fit"),
        ("Koki Machida", "CB", 16, "Union SG", "fit"),
        ("Hiroki Machida", "CB", 15, "Union SG", "fit"),
        ("Wataru Endo", "DM", 6, "Liverpool", "fit"),
        ("Daichi Kamada", "CM", 17, "Crystal Palace", "fit"),
        ("Hidemasa Morita", "CM", 5, "Sporting", "fit"),
        ("Reo Hatate", "CM", 13, "Celtic", "fit"),
        ("Ao Tanaka", "CM", 8, "Fortuna", "fit"),
        ("Takefusa Kubo", "RW", 11, "Real Sociedad", "fit"),
        ("Kaoru Mitoma", "LW", 7, "Brighton", "fit"),
        ("Ritsu Doan", "RW", 10, "Freiburg", "fit"),
        ("Ayase Ueda", "ST", 9, "Feyenoord", "fit"),
        ("Takumi Minamino", "FW", 18, "Monaco", "fit"),
        ("Daizen Maeda", "LW", 25, "Celtic", "fit"),
        ("Kyogo Furuhashi", "ST", 20, "Celtic", "fit"),
    ]},
    "KOR": {"coach": "Hong Myung-bo", "squad": [
        ("Kim Seung-gyu", "GK", 1, "Al Shabab", "fit"),
        ("Jo Hyeon-woo", "GK", 21, "Ulsan HD", "fit"),
        ("Song Bum-keun", "GK", 12, "Shonan Bellmare", "fit"),
        ("Kim Min-jae", "CB", 4, "Bayern", "fit"),
        ("Kim Young-gwon", "CB", 19, "Ulsan HD", "fit"),
        ("Jung Seung-hyun", "CB", 15, "Al Wasl", "fit"),
        ("Kwon Kyung-won", "CB", 5, "Al Arabi", "fit"),
        ("Seol Young-woo", "RB", 2, "Red Star", "fit"),
        ("Kim Tae-hwan", "RB", 23, "Jeonbuk", "fit"),
        ("Lee Ki-je", "LB", 3, "Suwon", "fit"),
        ("Kim Jin-su", "LB", 14, "Jeonbuk", "fit"),
        ("Hwang In-beom", "CM", 6, "Feyenoord", "fit"),
        ("Park Yong-woo", "DM", 8, "Al Ain", "fit"),
        ("Lee Kang-in", "AM", 18, "PSG", "fit"),
        ("Lee Jae-sung", "AM", 10, "Mainz", "fit"),
        ("Jung Woo-young", "CM", 13, "Al Khaleej", "fit"),
        ("Hong Hyun-seok", "CM", 22, "Gent", "fit"),
        ("Son Heung-min", "LW", 7, "Tottenham", "fit"),
        ("Hwang Hee-chan", "RW", 11, "Wolves", "fit"),
        ("Cho Gue-sung", "ST", 9, "Midtjylland", "fit"),
        ("Oh Hyeon-gyu", "ST", 17, "Celtic", "fit"),
        ("Bae Jun-ho", "AM", 20, "Stoke", "fit"),
        ("Yang Hyun-jun", "LW", 25, "Celtic", "fit"),
    ]},
    "CAN": {"coach": "Jesse Marsch", "squad": [
        ("Maxime Crepeau", "GK", 1, "Portland", "fit"),
        ("Dayne St Clair", "GK", 18, "Minnesota", "fit"),
        ("Jonathan Sirois", "GK", 22, "CF Montreal", "fit"),
        ("Alistair Johnston", "RB", 2, "Celtic", "fit"),
        ("Moise Bombito", "CB", 5, "Nice", "fit"),
        ("Derek Cornelius", "CB", 4, "Marseille", "fit"),
        ("Kamal Miller", "CB", 3, "Portland", "fit"),
        ("Joel Waterman", "CB", 15, "CF Montreal", "fit"),
        ("Alphonso Davies", "LB", 19, "Real Madrid", "fit"),
        ("Richie Laryea", "RB", 22, "Toronto FC", "fit"),
        ("Sam Adekugbe", "LB", 6, "Vancouver", "fit"),
        ("Stephen Eustaquio", "DM", 7, "Porto", "fit"),
        ("Ismael Kone", "CM", 8, "Rennes", "fit"),
        ("Jonathan Osorio", "CM", 21, "Toronto FC", "fit"),
        ("Ali Ahmed", "CM", 14, "Vancouver", "fit"),
        ("Mathieu Choiniere", "CM", 16, "CF Montreal", "fit"),
        ("Tajon Buchanan", "RW", 11, "Inter", "fit"),
        ("Jonathan David", "ST", 9, "Lille", "fit"),
        ("Cyle Larin", "ST", 10, "Mallorca", "fit"),
        ("Liam Millar", "LW", 23, "Basel", "fit"),
        ("Junior Hoilett", "RW", 17, "Hibernian", "fit"),
        ("Jacen Russell-Rowe", "ST", 20, "Columbus", "fit"),
        ("Theo Corbeanu", "RW", 25, "Granada", "fit"),
    ]},
    "COL": {"coach": "Nestor Lorenzo", "squad": [
        ("Camilo Vargas", "GK", 12, "Atlas", "fit"),
        ("David Ospina", "GK", 1, "Al Nassr", "fit"),
        ("Kevin Mier", "GK", 22, "Cruz Azul", "fit"),
        ("Davinson Sanchez", "CB", 23, "Galatasaray", "fit"),
        ("Yerry Mina", "CB", 13, "Cagliari", "fit"),
        ("Jhon Lucumi", "CB", 3, "Bologna", "fit"),
        ("Carlos Cuesta", "CB", 2, "Genk", "fit"),
        ("Daniel Munoz", "RB", 21, "Crystal Palace", "fit"),
        ("Santiago Arias", "RB", 4, "Bahia", "fit"),
        ("Johan Mojica", "LB", 17, "Osasuna", "fit"),
        ("Deiver Machado", "LB", 6, "Lens", "fit"),
        ("Jefferson Lerma", "DM", 16, "Crystal Palace", "fit"),
        ("Mateus Uribe", "CM", 5, "Al Sadd", "fit"),
        ("Richard Rios", "CM", 15, "Palmeiras", "fit"),
        ("Jhon Arias", "AM", 8, "Fluminense", "fit"),
        ("James Rodriguez", "AM", 10, "Sao Paulo", "fit"),
        ("Jorge Carrascal", "AM", 20, "Dynamo Moscow", "fit"),
        ("Luis Diaz", "LW", 7, "Liverpool", "fit"),
        ("Rafael Borre", "ST", 19, "Internacional", "fit"),
        ("Jhon Duran", "ST", 9, "Al Nassr", "fit"),
        ("Luis Sinisterra", "LW", 14, "Bournemouth", "fit"),
        ("Juanfer Quintero", "AM", 11, "Racing", "fit"),
        ("Jhon Cordoba", "ST", 24, "Krasnodar", "fit"),
    ]},
    "DEN": {"coach": "Brian Riemer", "squad": [
        ("Kasper Schmeichel", "GK", 1, "Anderlecht", "fit"),
        ("Mads Hermansen", "GK", 16, "Leicester", "fit"),
        ("Frederik Ronnow", "GK", 22, "Union Berlin", "fit"),
        ("Andreas Christensen", "CB", 6, "Barcelona", "fit"),
        ("Joachim Andersen", "CB", 2, "Fulham", "fit"),
        ("Jannik Vestergaard", "CB", 3, "Leicester", "fit"),
        ("Victor Nelsson", "CB", 4, "Galatasaray", "fit"),
        ("Rasmus Kristensen", "RB", 13, "Roma", "fit"),
        ("Joakim Maehle", "LB", 5, "Wolfsburg", "fit"),
        ("Victor Kristiansen", "LB", 17, "Leicester", "fit"),
        ("Alexander Bah", "RB", 18, "Benfica", "fit"),
        ("Pierre-Emile Hojbjerg", "DM", 23, "Marseille", "fit"),
        ("Christian Eriksen", "CM", 10, "Man United", "fit"),
        ("Morten Hjulmand", "CM", 21, "Sporting", "fit"),
        ("Mikkel Damsgaard", "CM", 14, "Brentford", "fit"),
        ("Matt O'Riley", "CM", 15, "Brighton", "fit"),
        ("Jesper Lindstrom", "AM", 7, "Everton", "fit"),
        ("Andreas Skov Olsen", "RW", 11, "Club Brugge", "fit"),
        ("Rasmus Hojlund", "ST", 9, "Man United", "fit"),
        ("Jonas Wind", "ST", 19, "Wolfsburg", "fit"),
        ("Yussuf Poulsen", "ST", 20, "RB Leipzig", "fit"),
        ("Kasper Dolberg", "ST", 12, "Anderlecht", "fit"),
        ("Mohamed Daramy", "LW", 25, "Reims", "fit"),
    ]},
    "SUI": {"coach": "Murat Yakin", "squad": [
        ("Yann Sommer", "GK", 1, "Inter", "fit"),
        ("Gregor Kobel", "GK", 21, "Dortmund", "fit"),
        ("Jonas Omlin", "GK", 12, "Gladbach", "fit"),
        ("Manuel Akanji", "CB", 5, "Man City", "fit"),
        ("Fabian Schar", "CB", 22, "Newcastle", "fit"),
        ("Nico Elvedi", "CB", 4, "Gladbach", "fit"),
        ("Ricardo Rodriguez", "CB", 13, "Real Betis", "fit"),
        ("Silvan Widmer", "RB", 2, "Mainz", "fit"),
        ("Kevin Mbabu", "RB", 16, "Augsburg", "fit"),
        ("Ulisses Garcia", "LB", 17, "Marseille", "fit"),
        ("Jordan Lotomba", "LB", 3, "Nice", "fit"),
        ("Granit Xhaka", "CM", 10, "Leverkusen", "fit"),
        ("Remo Freuler", "CM", 8, "Bologna", "fit"),
        ("Denis Zakaria", "DM", 6, "Monaco", "fit"),
        ("Michel Aebischer", "CM", 20, "Bologna", "fit"),
        ("Ardon Jashari", "CM", 15, "Club Brugge", "fit"),
        ("Xherdan Shaqiri", "AM", 23, "Basel", "fit"),
        ("Ruben Vargas", "LW", 14, "Augsburg", "fit"),
        ("Noah Okafor", "ST", 11, "AC Milan", "fit"),
        ("Breel Embolo", "ST", 7, "Monaco", "fit"),
        ("Zeki Amdouni", "ST", 19, "Benfica", "fit"),
        ("Dan Ndoye", "RW", 18, "Bologna", "fit"),
        ("Renato Steffen", "LW", 9, "Lugano", "fit"),
    ]},
    "MAR": {"coach": "Walid Regragui", "squad": [
        ("Yassine Bounou", "GK", 1, "Al Hilal", "fit"),
        ("Munir El Kajoui", "GK", 12, "Al Wehda", "fit"),
        ("Mehdi Benabid", "GK", 22, "FAR Rabat", "fit"),
        ("Achraf Hakimi", "RB", 2, "PSG", "fit"),
        ("Noussair Mazraoui", "LB", 3, "Man United", "fit"),
        ("Romain Saiss", "CB", 6, "Al Sadd", "fit"),
        ("Nayef Aguerd", "CB", 5, "West Ham", "fit"),
        ("Chadi Riad", "CB", 21, "Crystal Palace", "fit"),
        ("Yahya Attiat-Allah", "LB", 25, "Al Ahly", "fit"),
        ("Abdel Abqar", "CB", 14, "Alaves", "fit"),
        ("Mohamed Chibi", "RB", 15, "Pyramids", "fit"),
        ("Sofyan Amrabat", "DM", 4, "Fenerbahce", "fit"),
        ("Azzedine Ounahi", "CM", 8, "Marseille", "fit"),
        ("Bilal El Khannouss", "AM", 10, "Leicester", "fit"),
        ("Amir Richardson", "CM", 18, "Fiorentina", "fit"),
        ("Oussama El Azzouzi", "CM", 20, "Bologna", "fit"),
        ("Ismael Saibari", "CM", 23, "PSV", "fit"),
        ("Hakim Ziyech", "RW", 7, "Galatasaray", "fit"),
        ("Youssef En-Nesyri", "ST", 19, "Fenerbahce", "fit"),
        ("Amine Adli", "LW", 17, "Leverkusen", "fit"),
        ("Brahim Diaz", "AM", 11, "Real Madrid", "fit"),
        ("Eliesse Ben Seghir", "LW", 16, "Monaco", "fit"),
        ("Ayoub El Kaabi", "ST", 9, "Olympiacos", "fit"),
    ]},
    "SEN": {"coach": "Pape Thiaw", "squad": [
        ("Edouard Mendy", "GK", 16, "Al Ahli", "fit"),
        ("Seny Dieng", "GK", 1, "Middlesbrough", "fit"),
        ("Mory Diaw", "GK", 23, "Clermont", "fit"),
        ("Kalidou Koulibaly", "CB", 3, "Al Hilal", "fit"),
        ("Abdou Diallo", "CB", 4, "Al Arabi", "fit"),
        ("Moussa Niakhate", "CB", 22, "Lyon", "fit"),
        ("Ismail Jakobs", "LB", 14, "Galatasaray", "fit"),
        ("Fode Ballo-Toure", "LB", 12, "AC Milan", "fit"),
        ("Youssouf Sabaly", "RB", 21, "Real Betis", "fit"),
        ("Formose Mendy", "RB", 2, "Lorient", "fit"),
        ("Mikayil Ngor Faye", "CB", 19, "Barcelona B", "fit"),
        ("Idrissa Gueye", "CM", 5, "Everton", "fit"),
        ("Pape Matar Sarr", "CM", 17, "Tottenham", "fit"),
        ("Lamine Camara", "CM", 6, "Monaco", "fit"),
        ("Pape Gueye", "DM", 15, "Villarreal", "fit"),
        ("Habib Diarra", "CM", 20, "Strasbourg", "fit"),
        ("Sadio Mane", "LW", 10, "Al Nassr", "fit"),
        ("Ismaila Sarr", "RW", 18, "Crystal Palace", "fit"),
        ("Nicolas Jackson", "ST", 7, "Chelsea", "fit"),
        ("Boulaye Dia", "ST", 9, "Lazio", "fit"),
        ("Iliman Ndiaye", "AM", 13, "Everton", "fit"),
        ("Abdallah Sima", "ST", 11, "Brighton", "fit"),
        ("Krepin Diatta", "RW", 8, "Monaco", "fit"),
    ]},
    "SWE": {"coach": "Jon Dahl Tomasson", "squad": [
        ("Robin Olsen", "GK", 1, "Aston Villa", "fit"),
        ("Viktor Johansson", "GK", 12, "Stoke", "fit"),
        ("Leopold Wahlstedt", "GK", 23, "Blackburn", "fit"),
        ("Victor Lindelof", "CB", 3, "Man United", "fit"),
        ("Isak Hien", "CB", 4, "Atalanta", "fit"),
        ("Ludwig Augustinsson", "LB", 6, "Anderlecht", "fit"),
        ("Linus Wahlqvist", "RB", 2, "Pogon", "fit"),
        ("Emil Holm", "RB", 15, "Atalanta", "fit"),
        ("Gabriel Gudmundsson", "LB", 17, "Lille", "fit"),
        ("Carl Starfelt", "CB", 5, "Celta Vigo", "fit"),
        ("Hjalmar Ekdal", "CB", 13, "Burnley", "fit"),
        ("Emil Forsberg", "AM", 10, "NY Red Bulls", "fit"),
        ("Jens Cajuste", "CM", 8, "Ipswich", "fit"),
        ("Samuel Gustafson", "CM", 20, "Urawa Reds", "fit"),
        ("Hugo Larsson", "CM", 14, "Frankfurt", "fit"),
        ("Yasin Ayari", "CM", 16, "Brighton", "fit"),
        ("Mattias Svanberg", "CM", 7, "Wolfsburg", "fit"),
        ("Dejan Kulusevski", "RW", 21, "Tottenham", "fit"),
        ("Alexander Isak", "ST", 9, "Newcastle", "fit"),
        ("Viktor Gyokeres", "ST", 11, "Sporting", "fit"),
        ("Anthony Elanga", "LW", 18, "Nottm Forest", "fit"),
        ("Viktor Claesson", "RW", 19, "Copenhagen", "fit"),
        ("Robin Quaison", "ST", 22, "Al Ettifaq", "fit"),
    ]},
    "UKR": {"coach": "Serhiy Rebrov", "squad": [
        ("Anatoliy Trubin", "GK", 1, "Benfica", "fit"),
        ("Andriy Lunin", "GK", 23, "Real Madrid", "fit"),
        ("Dmytro Riznyk", "GK", 12, "Shakhtar", "fit"),
        ("Illya Zabarnyi", "CB", 25, "Bournemouth", "fit"),
        ("Mykola Matvienko", "CB", 22, "Shakhtar", "fit"),
        ("Oleksandr Svatok", "CB", 3, "Austin FC", "fit"),
        ("Vitaliy Mykolenko", "LB", 16, "Everton", "fit"),
        ("Yukhym Konoplya", "RB", 2, "Shakhtar", "fit"),
        ("Oleksandr Zinchenko", "LB", 17, "Arsenal", "fit"),
        ("Oleksandr Karavaiev", "RB", 21, "Dynamo Kyiv", "fit"),
        ("Bogdan Mykhaylichenko", "LB", 13, "Dynamo Kyiv", "fit"),
        ("Taras Stepanenko", "DM", 6, "Al Arabi", "fit"),
        ("Heorhiy Sudakov", "CM", 10, "Shakhtar", "fit"),
        ("Mykola Shaparenko", "CM", 14, "Dynamo Kyiv", "fit"),
        ("Serhiy Sydorchuk", "CM", 5, "Westerlo", "fit"),
        ("Ruslan Malinovskyi", "AM", 8, "Genoa", "fit"),
        ("Oleksandr Pikhalonok", "CM", 15, "Shakhtar", "fit"),
        ("Mykhailo Mudryk", "LW", 7, "Chelsea", "fit"),
        ("Artem Dovbyk", "ST", 9, "Roma", "fit"),
        ("Viktor Tsygankov", "RW", 11, "Girona", "fit"),
        ("Roman Yaremchuk", "ST", 18, "Olympiacos", "fit"),
        ("Vladyslav Vanat", "ST", 19, "Dynamo Kyiv", "fit"),
        ("Andriy Yarmolenko", "RW", 20, "Dynamo Kyiv", "fit"),
    ]},
    "SRB": {"coach": "Dragan Stojkovic", "squad": [
        ("Vanja Milinkovic-Savic", "GK", 1, "Torino", "fit"),
        ("Predrag Rajkovic", "GK", 12, "Al Ittihad", "fit"),
        ("Djordje Petrovic", "GK", 23, "Chelsea", "fit"),
        ("Nikola Milenkovic", "CB", 4, "Nottm Forest", "fit"),
        ("Strahinja Pavlovic", "CB", 2, "AC Milan", "fit"),
        ("Milos Veljkovic", "CB", 5, "Bremen", "fit"),
        ("Strahinja Erakovic", "CB", 13, "Zenit", "fit"),
        ("Nemanja Gudelj", "DM", 16, "Sevilla", "fit"),
        ("Srdjan Babic", "CB", 3, "Spartak Moscow", "fit"),
        ("Andrija Zivkovic", "RW", 14, "PAOK", "fit"),
        ("Filip Kostic", "LB", 11, "Juventus", "fit"),
        ("Sasa Lukic", "CM", 6, "Fulham", "fit"),
        ("Sergej Milinkovic-Savic", "CM", 20, "Al Hilal", "fit"),
        ("Ivan Ilic", "CM", 8, "Torino", "fit"),
        ("Lazar Samardzic", "AM", 17, "Atalanta", "fit"),
        ("Marko Grujic", "CM", 22, "Porto", "fit"),
        ("Filip Mladenovic", "LB", 15, "Panathinaikos", "fit"),
        ("Dusan Vlahovic", "ST", 9, "Juventus", "fit"),
        ("Aleksandar Mitrovic", "ST", 10, "Al Hilal", "fit"),
        ("Luka Jovic", "ST", 7, "AC Milan", "fit"),
        ("Dusan Tadic", "AM", 21, "Fenerbahce", "fit"),
        ("Veljko Birmancevic", "LW", 18, "Sparta Prague", "fit"),
        ("Petar Ratkov", "ST", 19, "RB Salzburg", "fit"),
    ]},
    "NOR": {"coach": "Stale Solbakken", "squad": [
        ("Orjan Nyland", "GK", 1, "Sevilla", "fit"),
        ("Mathias Dyngeland", "GK", 12, "Brann", "fit"),
        ("Egil Selvik", "GK", 23, "Haugesund", "fit"),
        ("Kristoffer Ajer", "CB", 4, "Brentford", "fit"),
        ("Leo Ostigard", "CB", 15, "Rennes", "fit"),
        ("Andreas Hanche-Olsen", "CB", 5, "Mainz", "fit"),
        ("Stefan Strandberg", "CB", 3, "Valerenga", "fit"),
        ("Julian Ryerson", "RB", 14, "Dortmund", "fit"),
        ("Marcus Pedersen", "RB", 2, "Torino", "fit"),
        ("Fredrik Bjorkan", "LB", 17, "Bodo/Glimt", "fit"),
        ("David Wolfe", "LB", 13, "AZ Alkmaar", "fit"),
        ("Martin Odegaard", "AM", 10, "Arsenal", "fit"),
        ("Sander Berge", "CM", 8, "Fulham", "fit"),
        ("Patrick Berg", "DM", 6, "Bodo/Glimt", "fit"),
        ("Kristian Thorstvedt", "CM", 16, "Sassuolo", "fit"),
        ("Mats Moller Daehli", "CM", 18, "Molde", "fit"),
        ("Oscar Bobb", "RW", 20, "Man City", "fit"),
        ("Antonio Nusa", "LW", 11, "RB Leipzig", "fit"),
        ("Erling Haaland", "ST", 9, "Man City", "fit"),
        ("Alexander Sorloth", "ST", 19, "Atletico Madrid", "fit"),
        ("Jorgen Strand Larsen", "ST", 7, "Wolves", "fit"),
        ("Aron Donnum", "RW", 22, "Toulouse", "fit"),
        ("Ola Solbakken", "LW", 21, "Empoli", "fit"),
    ]},
}

ALL_TEAMS_SMALL = {
    "PER": {"coach": "Jorge Fossati", "squad": [
        ("Pedro Gallese", "GK", 1, "Orlando City", "fit"), ("Carlos Caceda", "GK", 12, "Melgar", "fit"),
        ("Luis Abram", "CB", 5, "Atlanta United", "fit"), ("Alexander Callens", "CB", 22, "AEK Athens", "fit"),
        ("Miguel Araujo", "CB", 3, "Portland", "fit"), ("Luis Advincula", "RB", 17, "Boca Juniors", "fit"),
        ("Marcos Lopez", "LB", 6, "Feyenoord", "fit"), ("Miguel Trauco", "LB", 13, "Criciuma", "fit"),
        ("Renato Tapia", "DM", 16, "Celta Vigo", "fit"), ("Pedro Aquino", "CM", 23, "Santos Laguna", "fit"),
        ("Sergio Pena", "CM", 8, "Malmo", "fit"), ("Wilder Cartagena", "CM", 14, "Orlando City", "fit"),
        ("Piero Quispe", "AM", 20, "Pumas", "fit"), ("Christian Cueva", "AM", 10, "Alianza Lima", "fit"),
        ("Andre Carrillo", "RW", 18, "Al Qadsiah", "fit"), ("Bryan Reyna", "LW", 11, "Belgrano", "fit"),
        ("Gianluca Lapadula", "ST", 9, "Cagliari", "fit"), ("Paolo Guerrero", "ST", 7, "U. Cesar Vallejo", "fit"),
        ("Oliver Sonne", "RB", 2, "Silkeborg", "fit"), ("Joao Grimaldo", "LW", 19, "Sporting Cristal", "fit"),
        ("Franco Zanelatto", "RW", 15, "Alianza Lima", "fit"), ("Edison Flores", "AM", 21, "Universitario", "fit"),
        ("Alex Valera", "ST", 4, "Universitario", "fit"),
    ]},
    "HUN": {"coach": "Marco Rossi", "squad": [
        ("Peter Gulacsi", "GK", 1, "RB Leipzig", "fit"), ("Denes Dibusz", "GK", 12, "Ferencvaros", "fit"),
        ("Willi Orban", "CB", 6, "RB Leipzig", "fit"), ("Attila Szalai", "CB", 2, "Hoffenheim", "fit"),
        ("Adam Lang", "CB", 4, "Omonia", "fit"), ("Endre Botka", "RB", 14, "Ferencvaros", "fit"),
        ("Bendeguz Bolla", "RB", 7, "Wolfsberger", "fit"), ("Milos Kerkez", "LB", 11, "Bournemouth", "fit"),
        ("Zsolt Nagy", "LB", 25, "Puskas Akademia", "fit"), ("Callum Styles", "CM", 17, "West Brom", "fit"),
        ("Dominik Szoboszlai", "AM", 10, "Liverpool", "fit"), ("Andras Schafer", "CM", 13, "Union Berlin", "fit"),
        ("Daniel Gazdag", "AM", 16, "Philadelphia", "fit"), ("Laszlo Kleinheisler", "CM", 15, "Panathinaikos", "fit"),
        ("Loic Nego", "RW", 22, "Le Havre", "fit"), ("Roland Sallai", "LW", 20, "Galatasaray", "fit"),
        ("Barnabas Varga", "ST", 9, "Ferencvaros", "fit"), ("Martin Adam", "ST", 8, "Ulsan HD", "fit"),
        ("Kevin Csoboth", "ST", 23, "Ujpest", "fit"), ("Zsombor Gruber", "FW", 19, "Ferencvaros", "fit"),
    ]},
    "CHI": {"coach": "Ricardo Gareca", "squad": [
        ("Brayan Cortes", "GK", 1, "Colo-Colo", "fit"), ("Gabriel Arias", "GK", 12, "Racing", "fit"),
        ("Paulo Diaz", "CB", 3, "River Plate", "fit"), ("Guillermo Maripan", "CB", 5, "Torino", "fit"),
        ("Gary Medel", "CB", 17, "Boca Juniors", "fit"), ("Mauricio Isla", "RB", 4, "Independiente", "fit"),
        ("Thomas Galdames", "LB", 2, "Godoy Cruz", "fit"), ("Gabriel Suazo", "LB", 22, "Toulouse", "fit"),
        ("Erick Pulgar", "DM", 13, "Flamengo", "fit"), ("Rodrigo Echeverria", "CM", 18, "Huracan", "fit"),
        ("Marcelino Nunez", "CM", 7, "Norwich", "fit"), ("Arturo Vidal", "CM", 8, "Colo-Colo", "fit"),
        ("Dario Osorio", "RW", 14, "Brighton", "fit"), ("Diego Valdes", "AM", 10, "America", "fit"),
        ("Alexis Sanchez", "ST", 11, "Udinese", "fit"), ("Ben Brereton Diaz", "ST", 9, "Southampton", "fit"),
        ("Victor Davila", "ST", 19, "America", "fit"), ("Eduardo Vargas", "ST", 21, "Atletico Mineiro", "fit"),
    ]},
    "PAR": {"coach": "Daniel Garnero", "squad": [
        ("Antony Silva", "GK", 1, "Cerro Porteno", "fit"), ("Carlos Coronel", "GK", 12, "NY Red Bulls", "fit"),
        ("Gustavo Gomez", "CB", 15, "Palmeiras", "fit"), ("Fabian Balbuena", "CB", 3, "Dynamo Moscow", "fit"),
        ("Junior Alonso", "CB", 6, "Krasnodar", "fit"), ("Robert Rojas", "RB", 2, "River Plate", "fit"),
        ("Matias Espinoza", "LB", 4, "Libertad", "fit"), ("Andres Cubas", "DM", 14, "Vancouver", "fit"),
        ("Mathias Villasanti", "CM", 8, "Gremio", "fit"), ("Richard Sanchez", "CM", 21, "Racing", "fit"),
        ("Miguel Almiron", "AM", 10, "Newcastle", "fit"), ("Ramon Sosa", "LW", 11, "Nottm Forest", "fit"),
        ("Julio Enciso", "AM", 19, "Brighton", "fit"), ("Diego Gomez", "CM", 17, "Inter Miami", "fit"),
        ("Antonio Sanabria", "ST", 9, "Torino", "fit"), ("Adam Bareiro", "ST", 7, "River Plate", "fit"),
        ("Alejandro Romero", "RW", 20, "Al Ain", "fit"), ("Gabriel Avalos", "ST", 23, "Independiente", "fit"),
    ]},
    "ALG": {"coach": "Vladimir Petkovic", "squad": [
        ("Anthony Mandrea", "GK", 1, "Caen", "fit"), ("Moustapha Zeghba", "GK", 23, "Al Nassr", "fit"),
        ("Aissa Mandi", "CB", 2, "Villarreal", "fit"), ("Ramy Bensebaini", "CB", 21, "Dortmund", "fit"),
        ("Mohamed Amine Tougai", "CB", 4, "Esperance", "fit"), ("Youcef Atal", "RB", 20, "Nice", "fit"),
        ("Rayan Ait-Nouri", "LB", 3, "Wolves", "fit"), ("Ahmed Touba", "LB", 5, "Mechelen", "fit"),
        ("Ismael Bennacer", "CM", 6, "AC Milan", "fit"), ("Hicham Boudaoui", "CM", 22, "Nice", "fit"),
        ("Ramy Zerrouki", "DM", 14, "Feyenoord", "fit"), ("Nabil Bentaleb", "CM", 10, "Lille", "fit"),
        ("Riyad Mahrez", "RW", 7, "Al Ahli", "fit"), ("Said Benrahma", "LW", 17, "Lyon", "fit"),
        ("Mohamed Amoura", "ST", 9, "Wolfsburg", "fit"), ("Islam Slimani", "ST", 13, "Mechelen", "fit"),
        ("Yacine Brahimi", "LW", 11, "Al Gharafa", "fit"), ("Anis Hadj Moussa", "RW", 8, "Feyenoord", "fit"),
    ]},
    "NGA": {"coach": "Eric Chelle", "squad": [
        ("Stanley Nwabali", "GK", 23, "Chippa United", "fit"), ("Francis Uzoho", "GK", 1, "Omonia", "fit"),
        ("William Troost-Ekong", "CB", 5, "Al Kholood", "fit"), ("Calvin Bassey", "CB", 3, "Fulham", "fit"),
        ("Semi Ajayi", "CB", 6, "West Brom", "fit"), ("Ola Aina", "RB", 2, "Nottm Forest", "fit"),
        ("Bright Osayi-Samuel", "RB", 12, "Fenerbahce", "fit"), ("Zaidu Sanusi", "LB", 17, "Porto", "fit"),
        ("Wilfred Ndidi", "DM", 4, "Leicester", "fit"), ("Frank Onyeka", "CM", 8, "Augsburg", "fit"),
        ("Alex Iwobi", "CM", 18, "Fulham", "fit"), ("Raphael Onyedika", "DM", 15, "Club Brugge", "fit"),
        ("Victor Osimhen", "ST", 9, "Galatasaray", "fit"), ("Ademola Lookman", "LW", 11, "Atalanta", "fit"),
        ("Samuel Chukwueze", "RW", 21, "AC Milan", "fit"), ("Victor Boniface", "ST", 7, "Leverkusen", "fit"),
        ("Kelechi Iheanacho", "ST", 14, "Sevilla", "fit"), ("Moses Simon", "LW", 15, "Nantes", "fit"),
    ]},
    "QAT": {"coach": "Tintin Marquez", "squad": [
        ("Meshaal Barsham", "GK", 1, "Al Sadd", "fit"), ("Salah Zakaria", "GK", 21, "Al Duhail", "fit"),
        ("Boualem Khoukhi", "CB", 16, "Al Sadd", "fit"), ("Tarek Salman", "CB", 5, "Al Sadd", "fit"),
        ("Lucas Mendes", "CB", 12, "Al Wakrah", "fit"), ("Pedro Miguel", "RB", 2, "Al Sadd", "fit"),
        ("Homam Ahmed", "LB", 14, "Al Gharafa", "fit"), ("Mohammed Waad", "LB", 3, "Al Sadd", "fit"),
        ("Abdulaziz Hatem", "CM", 6, "Al Rayyan", "fit"), ("Jassem Gaber", "DM", 23, "Al Arabi", "fit"),
        ("Akram Afif", "LW", 11, "Al Sadd", "fit"), ("Almoez Ali", "ST", 19, "Al Duhail", "fit"),
        ("Hassan Al-Haydos", "AM", 10, "Al Sadd", "fit"), ("Yusuf Abdurisag", "RW", 17, "Al Sadd", "fit"),
        ("Ahmed Al Ganehi", "RW", 7, "Al Gharafa", "fit"), ("Mostafa Meshaal", "CM", 8, "Al Sadd", "fit"),
        ("Ahmed Fathy", "DM", 20, "Al Arabi", "fit"), ("Mohammed Muntari", "ST", 9, "Al Duhail", "fit"),
    ]},
    "IRN": {"coach": "Amir Ghalenoei", "squad": [
        ("Alireza Beiranvand", "GK", 1, "Antwerp", "fit"), ("Payam Niazmand", "GK", 12, "Sepahan", "fit"),
        ("Hossein Kanaanizadegan", "CB", 13, "Persepolis", "fit"), ("Shoja Khalilzadeh", "CB", 4, "Tractor", "fit"),
        ("Majid Hosseini", "CB", 19, "Kayserispor", "fit"), ("Ramin Rezaeian", "RB", 23, "Sepahan", "fit"),
        ("Milad Mohammadi", "LB", 5, "Adana Demirspor", "fit"), ("Ehsan Hajsafi", "LB", 3, "AEK Athens", "fit"),
        ("Saeid Ezatolahi", "DM", 6, "Shabab Al Ahli", "fit"), ("Sam Ghoddos", "CM", 14, "Brentford", "fit"),
        ("Alireza Jahanbakhsh", "RW", 7, "Feyenoord", "fit"), ("Mehdi Taremi", "ST", 9, "Inter", "fit"),
        ("Sardar Azmoun", "ST", 20, "Shabab Al Ahli", "fit"), ("Mehdi Ghayedi", "LW", 11, "Ittihad Kalba", "fit"),
        ("Mohammad Mohebi", "LW", 10, "Rostov", "fit"), ("Ali Gholizadeh", "AM", 17, "Lech Poznan", "fit"),
        ("Saman Ghoddos", "CM", 8, "Brentford", "fit"), ("Shahriyar Moghanlou", "ST", 22, "Sepahan", "fit"),
    ]},
    "EGY": {"coach": "Hossam Hassan", "squad": [
        ("Mohamed El Shenawy", "GK", 1, "Al Ahly", "fit"), ("Mohamed Sobhy", "GK", 16, "Zamalek", "fit"),
        ("Ahmed Hegazy", "CB", 6, "Neom SC", "fit"), ("Mohamed Abdelmonem", "CB", 24, "Nice", "fit"),
        ("Ramy Rabia", "CB", 2, "Al Ahly", "fit"), ("Mohamed Hany", "RB", 3, "Al Ahly", "fit"),
        ("Ahmed Abou El Fotouh", "LB", 12, "Zamalek", "fit"), ("Mohamed Hamdy", "LB", 13, "Pyramids", "fit"),
        ("Hamdi Fathy", "DM", 5, "Al Wakrah", "fit"), ("Marwan Attia", "CM", 17, "Al Ahly", "fit"),
        ("Emam Ashour", "CM", 8, "Al Ahly", "fit"), ("Zizo", "RW", 25, "Zamalek", "fit"),
        ("Mohamed Salah", "RW", 10, "Liverpool", "fit"), ("Mahmoud Trezeguet", "LW", 7, "Al Rayyan", "fit"),
        ("Mostafa Mohamed", "ST", 11, "Nantes", "fit"), ("Omar Marmoush", "ST", 22, "Man City", "fit"),
        ("Ahmed Sayed Zizo", "AM", 14, "Zamalek", "fit"), ("Ahmed Hassan Kouka", "ST", 9, "Rio Ave", "fit"),
    ]},
    "CRC": {"coach": "Gustavo Alfaro", "squad": [
        ("Keylor Navas", "GK", 1, "PSG", "fit"), ("Patrick Sequeira", "GK", 18, "Real Salt Lake", "fit"),
        ("Francisco Calvo", "CB", 8, "Hatayspor", "fit"), ("Juan Pablo Vargas", "CB", 3, "Millonarios", "fit"),
        ("Jeyland Mitchell", "CB", 4, "Feyenoord", "fit"), ("Keysher Fuller", "RB", 19, "Herediano", "fit"),
        ("Joseph Mora", "LB", 22, "Saprissa", "fit"), ("Ronald Matarrita", "LB", 15, "Alajuelense", "fit"),
        ("Celso Borges", "CM", 5, "Alajuelense", "fit"), ("Orlando Galo", "DM", 20, "Herediano", "fit"),
        ("Brandon Aguilera", "CM", 10, "Nottm Forest", "fit"), ("Aarón Suarez", "AM", 17, "Alajuelense", "fit"),
        ("Joel Campbell", "RW", 12, "Alajuelense", "fit"), ("Manfred Ugalde", "ST", 9, "Spartak Moscow", "fit"),
        ("Anthony Contreras", "ST", 7, "Riga FC", "fit"), ("Alvaro Zamora", "LW", 21, "Aris", "fit"),
        ("Warren Madrigal", "ST", 11, "Saprissa", "fit"), ("Jewison Bennette", "LW", 14, "Sunderland", "fit"),
    ]},
    "CIV": {"coach": "Emerse Fae", "squad": [
        ("Yahia Fofana", "GK", 1, "Angers", "fit"), ("Badra Ali Sangare", "GK", 23, "Sekhukhune", "fit"),
        ("Evan Ndicka", "CB", 3, "Roma", "fit"), ("Odilon Kossounou", "CB", 7, "Atalanta", "fit"),
        ("Ousmane Diomande", "CB", 5, "Sporting", "fit"), ("Willy Boly", "CB", 12, "Nottm Forest", "fit"),
        ("Serge Aurier", "RB", 17, "Galatasaray", "fit"), ("Ghislain Konan", "LB", 2, "Al Nassr", "fit"),
        ("Seko Fofana", "CM", 6, "Al Nassr", "fit"), ("Franck Kessie", "CM", 8, "Al Ahli", "fit"),
        ("Ibrahim Sangare", "DM", 18, "Nottm Forest", "fit"), ("Jean Michael Seri", "CM", 4, "Hull City", "fit"),
        ("Nicolas Pepe", "RW", 19, "Trabzonspor", "fit"), ("Simon Adingra", "LW", 14, "Brighton", "fit"),
        ("Sebastien Haller", "ST", 22, "Leganes", "fit"), ("Karim Konate", "ST", 9, "RB Salzburg", "fit"),
        ("Jonathan Bamba", "LW", 11, "Chicago Fire", "fit"), ("Oumar Diakite", "ST", 20, "Reims", "fit"),
    ]},
    "AUS": {"coach": "Tony Popovic", "squad": [
        ("Mat Ryan", "GK", 1, "Roma", "fit"), ("Joe Gauci", "GK", 12, "Aston Villa", "fit"),
        ("Harry Souttar", "CB", 19, "Sheff Utd", "fit"), ("Kye Rowles", "CB", 4, "Hearts", "fit"),
        ("Cameron Burgess", "CB", 3, "Ipswich", "fit"), ("Milos Degenek", "CB", 2, "Red Star", "fit"),
        ("Gethin Jones", "RB", 5, "Bolton", "fit"), ("Aziz Behich", "LB", 16, "Melbourne City", "fit"),
        ("Jordy Bos", "LB", 7, "Westerlo", "fit"), ("Jackson Irvine", "CM", 22, "St Pauli", "fit"),
        ("Ajdin Hrustic", "AM", 10, "Hellas Verona", "fit"), ("Connor Metcalfe", "CM", 8, "St Pauli", "fit"),
        ("Riley McGree", "CM", 14, "Middlesbrough", "fit"), ("Craig Goodwin", "LW", 23, "Al Wehda", "fit"),
        ("Martin Boyle", "RW", 6, "Hibernian", "fit"), ("Mitchell Duke", "ST", 15, "Machida", "fit"),
        ("Kusini Yengi", "ST", 9, "Portsmouth", "fit"), ("Nestory Irankunda", "RW", 11, "Bayern", "fit"),
    ]},
    "TUN": {"coach": "Faouzi Benzarti", "squad": [
        ("Bechir Ben Said", "GK", 1, "US Monastir", "fit"), ("Aymen Dahmen", "GK", 16, "Al Hazem", "fit"),
        ("Yassine Meriah", "CB", 3, "Esperance", "fit"), ("Montassar Talbi", "CB", 4, "Lorient", "fit"),
        ("Ali Abdi", "LB", 14, "Nice", "fit"), ("Wajdi Kechrida", "RB", 21, "Atromitos", "fit"),
        ("Hamza Rafia", "RB", 17, "Lecce", "fit"), ("Elyes Skhiri", "CM", 5, "Frankfurt", "fit"),
        ("Aissa Laidouni", "CM", 6, "Al Wakrah", "fit"), ("Mohamed Ali Ben Romdhane", "CM", 15, "Ferencvaros", "fit"),
        ("Anis Ben Slimane", "CM", 8, "Sheff Utd", "fit"), ("Hannibal Mejbri", "AM", 10, "Burnley", "fit"),
        ("Naim Sliti", "RW", 23, "Al Ettifaq", "fit"), ("Youssef Msakni", "LW", 7, "Al Arabi", "fit"),
        ("Wahbi Khazri", "ST", 11, "Montpellier", "fit"), ("Seifeddine Jaziri", "ST", 19, "Zamalek", "fit"),
        ("Sayfallah Ltaief", "LW", 13, "Basel", "fit"), ("Elias Achouri", "RW", 18, "Copenhagen", "fit"),
    ]},
    "PAN": {"coach": "Thomas Christiansen", "squad": [
        ("Luis Mejia", "GK", 1, "Nacional", "fit"), ("Orlando Mosquera", "GK", 12, "Al Fahya", "fit"),
        ("Fidel Escobar", "CB", 4, "Saprissa", "fit"), ("Jose Cordoba", "CB", 3, "Norwich", "fit"),
        ("Carlos Harvey", "CB", 5, "Minnesota", "fit"), ("Michael Amir Murillo", "RB", 23, "Marseille", "fit"),
        ("Cesar Blackman", "RB", 2, "Slovan Bratislava", "fit"), ("Eric Davis", "LB", 15, "FC Kosice", "fit"),
        ("Anibal Godoy", "DM", 20, "Nashville", "fit"), ("Adalberto Carrasquilla", "CM", 8, "Pumas", "fit"),
        ("Cristian Martinez", "CM", 6, "Al Jandal", "fit"), ("Puma Rodriguez", "AM", 10, "Pachuca", "fit"),
        ("Edgar Barcenas", "RW", 17, "Mazatlan", "fit"), ("Ismael Diaz", "ST", 9, "U. Catolica", "fit"),
        ("Freddy Gondola", "LW", 13, "Maccabi Bnei Reineh", "fit"), ("Jose Fajardo", "ST", 11, "U. Catolica", "fit"),
        ("Roderick Miller", "CB", 16, "FC Turan", "fit"), ("Alfredo Stephens", "ST", 18, "Ironi Kiryat Shmona", "fit"),
    ]},
    "CMR": {"coach": "Marc Brys", "squad": [
        ("Andre Onana", "GK", 23, "Man United", "fit"), ("Fabrice Ondoa", "GK", 1, "Nimes", "fit"),
        ("Jean-Charles Castelletto", "CB", 21, "Nantes", "fit"), ("Christopher Wooh", "CB", 4, "Rennes", "fit"),
        ("Nouhou Tolo", "LB", 25, "Seattle Sounders", "fit"), ("Collins Fai", "RB", 19, "Radnicki", "fit"),
        ("Enzo Tchato", "RB", 2, "Montpellier", "fit"), ("Harold Moukoudi", "CB", 5, "AEK Athens", "fit"),
        ("Andre-Frank Zambo Anguissa", "CM", 8, "Napoli", "fit"), ("Carlos Baleba", "CM", 17, "Brighton", "fit"),
        ("Pierre Kunde", "CM", 11, "Atromitos", "fit"), ("Martin Hongla", "DM", 18, "Real Valladolid", "fit"),
        ("Bryan Mbeumo", "RW", 20, "Brentford", "fit"), ("Vincent Aboubakar", "ST", 10, "Besiktas", "fit"),
        ("Georges-Kevin Nkoudou", "LW", 7, "Damac", "fit"), ("Karl Toko Ekambi", "ST", 12, "Al Ettifaq", "fit"),
        ("Moumi Ngamaleu", "LW", 6, "Dynamo Moscow", "fit"), ("Eric Maxim Choupo-Moting", "ST", 13, "NY Red Bulls", "fit"),
    ]},
    "GHA": {"coach": "Otto Addo", "squad": [
        ("Lawrence Ati-Zigi", "GK", 1, "St Gallen", "fit"), ("Jojo Wollacott", "GK", 12, "Crawley", "fit"),
        ("Mohammed Salisu", "CB", 4, "Monaco", "fit"), ("Alexander Djiku", "CB", 6, "Fenerbahce", "fit"),
        ("Daniel Amartey", "CB", 27, "Besiktas", "fit"), ("Tariq Lamptey", "RB", 2, "Brighton", "fit"),
        ("Gideon Mensah", "LB", 14, "Auxerre", "fit"), ("Alidu Seidu", "RB", 3, "Rennes", "fit"),
        ("Thomas Partey", "DM", 5, "Arsenal", "fit"), ("Mohammed Kudus", "AM", 20, "West Ham", "fit"),
        ("Elisha Owusu", "CM", 21, "Gent", "fit"), ("Salis Abdul Samed", "DM", 15, "Sunderland", "fit"),
        ("Abdul Fatawu Issahaku", "RW", 7, "Leicester", "fit"), ("Jordan Ayew", "ST", 9, "Leicester", "fit"),
        ("Inaki Williams", "ST", 19, "Athletic Bilbao", "fit"), ("Antoine Semenyo", "LW", 25, "Bournemouth", "fit"),
        ("Osman Bukari", "RW", 13, "Austin FC", "fit"), ("Ernest Nuamah", "LW", 18, "Lyon", "fit"),
    ]},
    "KSA": {"coach": "Roberto Mancini", "squad": [
        ("Mohammed Al Owais", "GK", 21, "Al Hilal", "fit"), ("Ahmed Al Kassar", "GK", 1, "Al Hilal", "fit"),
        ("Ali Al Bulayhi", "CB", 5, "Al Hilal", "fit"), ("Hassan Tambakti", "CB", 17, "Al Hilal", "fit"),
        ("Abdulelah Al Amri", "CB", 3, "Al Nassr", "fit"), ("Saud Abdulhamid", "RB", 2, "Roma", "fit"),
        ("Yasser Al Shahrani", "LB", 13, "Al Hilal", "fit"), ("Mohammed Al Burayk", "RB", 6, "Al Hilal", "fit"),
        ("Salman Al Faraj", "CM", 7, "Al Hilal", "fit"), ("Abdulelah Al Malki", "DM", 16, "Al Hilal", "fit"),
        ("Mohamed Kanno", "CM", 23, "Al Hilal", "fit"), ("Nasser Al Dawsari", "CM", 15, "Al Hilal", "fit"),
        ("Salem Al Dawsari", "LW", 10, "Al Hilal", "fit"), ("Firas Al Buraikan", "ST", 11, "Al Ahli", "fit"),
        ("Abdullah Al Hamdan", "ST", 9, "Al Hilal", "fit"), ("Fahad Al Muwallad", "RW", 8, "Al Shabab", "fit"),
        ("Sultan Al Ghannam", "RB", 12, "Al Nassr", "fit"), ("Abdulrahman Ghareeb", "RW", 18, "Al Nassr", "fit"),
    ]},
    "IRQ": {"coach": "Jesus Casas", "squad": [
        ("Jalal Hassan", "GK", 1, "Al Zawraa", "fit"), ("Ahmed Basil", "GK", 12, "Al Shorta", "fit"),
        ("Rebin Sulaka", "CB", 4, "Bhayangkara", "fit"), ("Saad Natiq", "CB", 3, "Al Quwa Al Jawiya", "fit"),
        ("Ali Adnan", "LB", 15, "Al Najaf", "fit"), ("Mustafa Saadoun", "RB", 2, "Al Quwa Al Jawiya", "fit"),
        ("Ahmed Yahya", "RB", 6, "Al Shorta", "fit"), ("Hussein Ali", "CB", 5, "Al Shorta", "fit"),
        ("Amir Al Ammari", "CM", 20, "Karlsruher", "fit"), ("Ibrahim Bayesh", "CM", 8, "Al Quwa Al Jawiya", "fit"),
        ("Zidane Iqbal", "CM", 14, "Utrecht", "fit"), ("Osama Rashid", "DM", 16, "Vizela", "fit"),
        ("Ali Jasim", "LW", 11, "Como", "fit"), ("Aymen Hussein", "ST", 18, "Al Quwa Al Jawiya", "fit"),
        ("Mohanad Ali", "ST", 10, "Al Shorta", "fit"), ("Bashar Resan", "AM", 17, "Al Quwa Al Jawiya", "fit"),
        ("Ali Al Hamadi", "ST", 9, "Ipswich", "fit"), ("Youssef Amyn", "LW", 21, "FC Twente", "fit"),
    ]},
    "UAE": {"coach": "Paulo Bento", "squad": [
        ("Khalid Eisa", "GK", 17, "Al Ain", "fit"), ("Ali Khaseif", "GK", 1, "Al Jazira", "fit"),
        ("Khalifa Al Hammadi", "CB", 12, "Al Jazira", "fit"), ("Mohamed Al Attas", "CB", 3, "Al Jazira", "fit"),
        ("Bader Nasser", "RB", 19, "Shabab Al Ahli", "fit"), ("Khaled Ibrahim", "LB", 2, "Sharjah", "fit"),
        ("Zayed Sultan", "RB", 9, "Al Jazira", "fit"), ("Abdulla Idrees", "CB", 4, "Al Jazira", "fit"),
        ("Abdalla Ramadan", "CM", 15, "Al Jazira", "fit"), ("Majid Rashid", "DM", 18, "Sharjah", "fit"),
        ("Tahnoon Al Zaabi", "CM", 8, "Al Wahda", "fit"), ("Yahia Nader", "CM", 6, "Al Ain", "fit"),
        ("Caio Canedo", "ST", 7, "Al Wasl", "fit"), ("Fabio De Lima", "RW", 10, "Al Wasl", "fit"),
        ("Ali Mabkhout", "ST", 11, "Al Nasr", "fit"), ("Harib Abdalla", "LW", 20, "Shabab Al Ahli", "fit"),
        ("Sultan Adil", "ST", 16, "Sharjah", "fit"), ("Yahya Al Ghassani", "RW", 5, "Shabab Al Ahli", "fit"),
    ]},
    "NZL": {"coach": "Darren Bazeley", "squad": [
        ("Max Crocombe", "GK", 1, "Burton", "fit"), ("Alex Paulsen", "GK", 12, "AFC Wimbledon", "fit"),
        ("Michael Boxall", "CB", 2, "Minnesota", "fit"), ("Nando Pijnaker", "CB", 3, "Sligo Rovers", "fit"),
        ("Tyler Bindon", "CB", 4, "Reading", "fit"), ("Bill Tuiloma", "RB", 5, "Charlotte", "fit"),
        ("Liberato Cacace", "LB", 13, "Empoli", "fit"), ("Dalton Wilkins", "LB", 15, "FC Helsingor", "fit"),
        ("Joe Bell", "CM", 8, "Viking", "fit"), ("Matthew Garbett", "CM", 14, "NAC Breda", "fit"),
        ("Marko Stamenic", "CM", 6, "Olympiacos", "fit"), ("Sarpreet Singh", "AM", 10, "Hansa Rostock", "fit"),
        ("Chris Wood", "ST", 9, "Nottm Forest", "fit"), ("Ben Waine", "ST", 11, "Mansfield", "fit"),
        ("Kosta Barbarouses", "RW", 7, "Wellington Phoenix", "fit"), ("Callum McCowatt", "LW", 20, "Silkeborg", "fit"),
        ("Elijah Just", "RW", 18, "St Polten", "fit"), ("Max Mata", "ST", 23, "Auckland FC", "fit"),
    ]},
    "ECU": {"coach": "Sebastian Beccacece", "squad": [
        ("Hernan Galindez", "GK", 1, "Huracan", "fit"), ("Moises Ramirez", "GK", 12, "Independiente", "fit"),
        ("Piero Hincapie", "CB", 3, "Leverkusen", "fit"), ("Willian Pacho", "CB", 6, "PSG", "fit"),
        ("Felix Torres", "CB", 2, "Corinthians", "fit"), ("Angelo Preciado", "RB", 17, "Sparta Prague", "fit"),
        ("Pervis Estupinan", "LB", 7, "Brighton", "fit"), ("Anibal Chala", "LB", 4, "Barcelona SC", "fit"),
        ("Moises Caicedo", "CM", 23, "Chelsea", "fit"), ("Carlos Gruezo", "DM", 20, "San Jose", "fit"),
        ("Alan Franco", "CM", 21, "Atletico Mineiro", "fit"), ("Jose Cifuentes", "CM", 5, "Aris", "fit"),
        ("Kendry Paez", "AM", 14, "Independiente", "fit"), ("Gonzalo Plata", "RW", 19, "Flamengo", "fit"),
        ("Jeremy Sarmiento", "LW", 10, "Burnley", "fit"), ("Enner Valencia", "ST", 13, "Internacional", "fit"),
        ("Kevin Rodriguez", "ST", 11, "Union SG", "fit"), ("John Mercado", "RW", 15, "AVS", "fit"),
    ]},
    "SCO": {"coach": "Steve Clarke", "squad": [
        ("Angus Gunn", "GK", 1, "Norwich", "fit"), ("Liam Kelly", "GK", 12, "Rangers", "fit"),
        ("Andrew Robertson", "LB", 3, "Liverpool", "fit"), ("Kieran Tierney", "CB", 6, "Arsenal", "doubtful"),
        ("Jack Hendry", "CB", 13, "Al Ettifaq", "fit"), ("Scott McKenna", "CB", 15, "Nottm Forest", "fit"),
        ("Nathan Patterson", "RB", 2, "Everton", "fit"), ("Anthony Ralston", "RB", 22, "Celtic", "fit"),
        ("Greg Taylor", "LB", 25, "Celtic", "fit"), ("Callum McGregor", "CM", 8, "Celtic", "fit"),
        ("Scott McTominay", "CM", 4, "Napoli", "fit"), ("Billy Gilmour", "CM", 17, "Brighton", "fit"),
        ("John McGinn", "AM", 7, "Aston Villa", "fit"), ("Ryan Christie", "AM", 11, "Bournemouth", "fit"),
        ("Stuart Armstrong", "CM", 14, "Vancouver", "fit"), ("Che Adams", "ST", 9, "Torino", "fit"),
        ("Lyndon Dykes", "ST", 10, "Birmingham", "fit"), ("Lawrence Shankland", "ST", 21, "Hearts", "fit"),
        ("Lewis Ferguson", "AM", 19, "Bologna", "injured"), ("Ben Doak", "RW", 18, "Middlesbrough", "fit"),
        ("Tommy Conway", "ST", 24, "Middlesbrough", "fit"),
    ]},
}
ALL_TEAMS.update(ALL_TEAMS_SMALL)

async def main():
    import os
    db_url = os.getenv('DATABASE_URL', 'postgresql+asyncpg://wcp:wcp_dev@postgres:5432/world_cup_predictor')
    engine = create_async_engine(db_url)
    session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with session() as db:
        for code, data in ALL_TEAMS.items():
            result = await db.execute(select(Team).where(Team.fifa_code == code))
            team = result.scalar_one_or_none()
            if team:
                squad_list = []
                unavailable = []
                for name, pos, num, club, status in data['squad']:
                    player = {"name": name, "position": pos, "number": num, "club": club}
                    squad_list.append(player)
                    if status != "fit":
                        issue_type = "injury" if status == "injured" else "fitness_concern"
                        unavailable.append({
                            "name": name, "position": pos, "number": num,
                            "type": issue_type,
                            "contribution_weight": 0.08 if pos in ("GK", "ST") else 0.05
                        })

                team.coach_name = data['coach']
                team.squad_json = squad_list
                team.availability_json = {"unavailable": unavailable} if unavailable else {}
                print(f"Updated {team.name}: {len(squad_list)} players, coach={data['coach']}, unavailable={len(unavailable)}")
        await db.commit()
    await engine.dispose()
    print("Done — all 48 teams fully populated")

asyncio.run(main())
